// Generated by `pnpm packages:sync` from the opendatasoft library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { OPENDATASOFT_DEPLOYMENT, OPENDATASOFT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/opendatasoft";

export default libraryGatekeeper<Env>(OPENDATASOFT_DEPLOYMENT, OPENDATASOFT_EXAMPLES);
