// Generated by `pnpm packages:sync` from the feeds whose first topic is mobility; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { CARRIS_DEPLOYMENT, CARRIS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/carris";
import { GBFS_DEPLOYMENT, GBFS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/gbfs";
import { GTFS_DEPLOYMENT, GTFS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/gtfs";
import { INE_DEPLOYMENT, INE_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ine";
import { METROLISBOA_DEPLOYMENT, METRO_LISBOA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/metrolisboa";

export default topicGatekeeper<Env>(
  "mobility",
  [CARRIS_DEPLOYMENT, GBFS_DEPLOYMENT, GTFS_DEPLOYMENT, INE_DEPLOYMENT, METROLISBOA_DEPLOYMENT],
  [...CARRIS_EXAMPLES, ...GBFS_EXAMPLES, ...GTFS_EXAMPLES, ...INE_EXAMPLES, ...METRO_LISBOA_EXAMPLES],
);
