import type { ReactNode } from "react";
import { fmt } from "../lib/format";
import { inLocale } from "../lib/locale";

/** The analytics page: who uses open-data.pt, for what, from where and when. */
export const ANALYTICS = inLocale({
  en: {
    windows: { "1": "24 hours", "7": "7 days", "30": "30 days", "90": "90 days" },
    overLast: (days: number) => (days === 1 ? "over the last 24 hours" : `over the last ${days} days`),
    views: { all: "Everything", web: "Website", api: "API", mcp: "MCP" },
    /** MCP's JSON-RPC methods in words. */
    calls: {
      initialize: "Connected",
      "notifications/initialized": "Connection confirmed",
      "tools/list": "Listed the tools",
      "tools/call execute": "Ran code against the API",
      "tools/call search": "Searched the API description",
      ping: "Checked the server is up",
    },
    otherRequest: "Other request",
    lines: {
      web: "Page views",
      api: "API requests",
      mcp: "MCP messages",
      browsers: "Browsers",
      scripts: "Scripts and apps",
      machines: "AI agents and crawlers",
    },
    kinds: { browser: "Browser", library: "Script", "ai-agent": "AI agent", crawler: "Crawler", unknown: "Unknown" },
    mediums: { search: "Search", social: "Social", email: "Email", chatbot: "AI assistant", paid: "Ad" },
    surfaces: { web: "website", api: "API", "mcp-read": "MCP" },
    /** What a topic, publisher or licence row is, by the page it was read on. */
    subjectTags: { catalog: "catalog", publisher: "publisher", licence: "licence" },
    torNetwork: "Tor network",
    unknown: "Unknown",
    eyebrow: "Analytics",
    title: "How open-data.pt is used",
    intro: (retentionDays: number, apiLink: ReactNode) => (
      <>
        Requests to the website, the API and the MCP server, counted as they are answered. No cookies, no IP addresses and no visitor identifiers are kept: only what was asked for,
        by what kind of client, from which country. The numbers are refreshed every half hour and go back {retentionDays} days. The same data is at {apiLink}.
      </>
    ),
    whatToShow: "What to show",
    timeWindow: "Time window",
    disabledTitle: "Analytics are not switched on yet",
    disabledDescription: "This deployment does not count its requests yet. Check back later.",
    what: "the usage numbers",
    totals: "Totals",
    pageViews: "Page views",
    apiRequests: "API requests",
    fromOutside: "from outside this website",
    mcpMessages: "MCP messages",
    mcpReadsNote: (reads: string) => `and ${reads} API reads from MCP code runs`,
    peopleAndMachines: "People and machines",
    peopleNote: (machines: number) => `from browsers; ${machines}% from AI agents and crawlers`,
    requests: "Requests",
    messages: "Messages",
    clients: "Clients",
    kindsNote: (kinds: string) => `${kinds} kinds`,
    edgeCache: "Served from the edge cache",
    rateLimited: (count: string) => `${count} refused by the rate limit`,
    markdown: "Read as Markdown",
    markdownNote: "pages fetched by agents asking for text/markdown",
    codeRunReads: "API reads from code runs",
    codeRunReadsNote: "each code run can read several",
    serverErrors: "Server errors",
    errorShare: (percent: string, web: boolean) => `${percent}% of ${web ? "page views" : "requests"}`,
    whoEyebrow: "Who",
    whoTitle: "Clients",
    whoBody: "Named from each request’s User-Agent. Scripts are HTTP libraries and command-line tools; AI agents fetch for an assistant or train one.",
    kindsOfClient: "Kinds of client",
    mcpCalls: "MCP calls",
    mcpCallsNote: "What assistants asked the MCP server for, and the names clients gave when they connected.",
    whatEyebrow: "What",
    whatTitle: "Datasets and routes",
    whatMcp: "What MCP code runs read from the API.",
    whatAll: "Datasets opened on the website, read through the API or read by MCP code runs.",
    whatMost: "What was asked for most.",
    datasets: "Datasets",
    pages: "Pages",
    routes: "Routes",
    meanTime: "Mean time to answer beside each.",
    subjects: "Topics, publishers and licences",
    whereEyebrow: "Where",
    whereTitle: "Countries and referrers",
    whereBody: "Countries as Cloudflare locates each client. Referrers are the sites visitors followed a link from, named with what kind of site they are.",
    countries: "Countries",
    referrers: "Referrers",
    noReferrers: "No request came with a link from another site.",
    mapTitle: "Where the requests came from",
    requestCount: (count: number) => `${fmt.int(count)} requests`,
    whenEyebrow: "When",
    perHour: "Requests per hour",
    perDay: "Requests per day",
    whenAll: "Page views, API requests and MCP messages.",
    whenKinds: "By kind of client.",
    utcDays: " Days are UTC days.",
    localHours: " Hours in your local time.",
    legend: "Legend",
    showTable: "Show as a table",
    hour: "Hour",
    day: "Day",
    nothingCounted: "Nothing counted in this window.",
    showFewer: "Show fewer",
    showAll: (count: string) => `Show all ${count}`,
  },
  pt: {
    windows: { "1": "24 horas", "7": "7 dias", "30": "30 dias", "90": "90 dias" },
    overLast: (days: number) => (days === 1 ? "nas últimas 24 horas" : `nos últimos ${days} dias`),
    views: { all: "Tudo", web: "Site", api: "API", mcp: "MCP" },
    calls: {
      initialize: "Ligou-se",
      "notifications/initialized": "Ligação confirmada",
      "tools/list": "Listou as ferramentas",
      "tools/call execute": "Executou código na API",
      "tools/call search": "Pesquisou a descrição da API",
      ping: "Verificou se o servidor está ativo",
    },
    otherRequest: "Outro pedido",
    lines: {
      web: "Visualizações de páginas",
      api: "Pedidos à API",
      mcp: "Mensagens MCP",
      browsers: "Navegadores",
      scripts: "Scripts e aplicações",
      machines: "Agentes de IA e rastreadores",
    },
    kinds: { browser: "Navegador", library: "Script", "ai-agent": "Agente de IA", crawler: "Rastreador", unknown: "Desconhecido" },
    mediums: { search: "Pesquisa", social: "Redes sociais", email: "Email", chatbot: "Assistente de IA", paid: "Anúncio" },
    surfaces: { web: "site", api: "API", "mcp-read": "MCP" },
    subjectTags: { catalog: "tema", publisher: "entidade", licence: "licença" },
    torNetwork: "Rede Tor",
    unknown: "Desconhecido",
    eyebrow: "Estatísticas",
    title: "Como o open-data.pt é usado",
    intro: (retentionDays: number, apiLink: ReactNode) => (
      <>
        Pedidos ao site, à API e ao servidor MCP, contados à medida que são respondidos. Não guardamos cookies, endereços IP nem identificadores de visitantes: só o que foi pedido,
        por que tipo de cliente e de que país. Os números são atualizados a cada meia hora e recuam {retentionDays} dias. Os mesmos dados estão em {apiLink}.
      </>
    ),
    whatToShow: "O que mostrar",
    timeWindow: "Período",
    disabledTitle: "As estatísticas ainda não estão ligadas",
    disabledDescription: "Esta instalação ainda não conta os pedidos que recebe. Volte mais tarde.",
    what: "os números de utilização",
    totals: "Totais",
    pageViews: "Visualizações de páginas",
    apiRequests: "Pedidos à API",
    fromOutside: "de fora deste site",
    mcpMessages: "Mensagens MCP",
    mcpReadsNote: (reads: string) => `e ${reads} leituras da API por código executado via MCP`,
    peopleAndMachines: "Pessoas e máquinas",
    peopleNote: (machines: number) => `de navegadores; ${machines}% de agentes de IA e rastreadores`,
    requests: "Pedidos",
    messages: "Mensagens",
    clients: "Clientes",
    kindsNote: (kinds: string) => `${kinds} tipos`,
    edgeCache: "Servidos pela cache da rede",
    rateLimited: (count: string) => `${count} recusados pelo limite de pedidos`,
    markdown: "Lidas em Markdown",
    markdownNote: "páginas obtidas por agentes que pedem text/markdown",
    codeRunReads: "Leituras da API por código executado",
    codeRunReadsNote: "cada execução de código pode ler várias",
    serverErrors: "Erros do servidor",
    errorShare: (percent: string, web: boolean) => `${percent}% ${web ? "das visualizações de páginas" : "dos pedidos"}`,
    whoEyebrow: "Quem",
    whoTitle: "Clientes",
    whoBody:
      "Identificados pelo User-Agent de cada pedido. Os scripts são bibliotecas HTTP e ferramentas de linha de comandos; os agentes de IA vão buscar dados para um assistente ou para treinar um.",
    kindsOfClient: "Tipos de cliente",
    mcpCalls: "Chamadas MCP",
    mcpCallsNote: "O que os assistentes pediram ao servidor MCP e os nomes que os clientes deram ao ligar-se.",
    whatEyebrow: "O quê",
    whatTitle: "Conjuntos de dados e rotas",
    whatMcp: "O que o código executado via MCP leu da API.",
    whatAll: "Conjuntos de dados abertos no site, lidos através da API ou lidos por código executado via MCP.",
    whatMost: "O que foi mais pedido.",
    datasets: "Conjuntos de dados",
    pages: "Páginas",
    routes: "Rotas",
    meanTime: "O tempo médio de resposta ao lado de cada uma.",
    subjects: "Temas, entidades publicadoras e licenças",
    whereEyebrow: "Onde",
    whereTitle: "Países e sites de origem",
    whereBody: "Países tal como a Cloudflare localiza cada cliente. Os sites de origem são aqueles de onde os visitantes seguiram uma ligação, com o tipo de site que são.",
    countries: "Países",
    referrers: "Sites de origem",
    noReferrers: "Nenhum pedido veio de uma ligação noutro site.",
    mapTitle: "De onde vieram os pedidos",
    requestCount: (count: number) => `${fmt.int(count)} ${count === 1 ? "pedido" : "pedidos"}`,
    whenEyebrow: "Quando",
    perHour: "Pedidos por hora",
    perDay: "Pedidos por dia",
    whenAll: "Visualizações de páginas, pedidos à API e mensagens MCP.",
    whenKinds: "Por tipo de cliente.",
    utcDays: " Os dias são dias UTC.",
    localHours: " As horas estão na sua hora local.",
    legend: "Legenda",
    showTable: "Mostrar como tabela",
    hour: "Hora",
    day: "Dia",
    nothingCounted: "Nada contado neste período.",
    showFewer: "Mostrar menos",
    showAll: (count: string) => `Mostrar todos (${count})`,
  },
});
