import { fmt, plural } from "../lib/format";
import { inLocale } from "../lib/locale";
import { LISTINGS } from "./listings";

/** The home page. */
export const HOME = inLocale({
  en: {
    eyebrow: "Portuguese public data",
    heading: { before: "Public data from Portugal, ", emphasis: "in one place", after: "." },
    intro:
      "Datasets published by Portuguese institutions and operators, collected from where they publish them and served in one consistent format. Free to use, with no key and no account. Every dataset names its publisher and links back to the source.",
    searchPlaceholder: "Search datasets: metro, fuel prices, population…",
    searchLabel: "Search datasets",
    search: "Search",
    browse: "Browse the whole catalog",
    useApi: "Use the API",
    connectAssistant: "Connect an AI assistant",
    pressBefore: "or press",
    pressAfter: "anywhere",
    liveLabel: "Collected in the last minutes",
    rightNow: "Right now",
    checking: "Checking collection…",
    everythingCollecting: "Everything collecting",
    sourcesNotCollecting: (count: number) => `${plural(count, "source")} not collecting`,
    loadingLive: "Loading live data…",
    atAGlance: "At a glance",
    fromPublishers: (count: number) => `from ${LISTINGS.publishers(count)}`,
    publishers: "Publishers",
    institutionsAndOperators: "institutions and operators",
    nearRealTime: "Near real time",
    severalTimesAnHour: "collected several times an hour",
    collection: "Collection",
    allCollecting: "All collecting",
    notCollecting: (count: number) => `${fmt.int(count)} not collecting`,
    everythingCollected: "everything is being collected",
    seeStatus: "see the status page",
    topicsEyebrow: "Topics",
    topicsTitle: "Browse by topic",
    recentEyebrow: "Recently updated",
    recentTitle: "New from the publishers",
    recentIntro: "Tables and series whose publisher released new or changed data most recently. What changes several times an hour is at the top of this page.",
    publishersTitle: "Where the data comes from",
    allPublishers: "All publishers",
    loading: "Loading",
  },
  pt: {
    eyebrow: "Dados públicos portugueses",
    heading: { before: "Dados públicos de Portugal, ", emphasis: "num só lugar", after: "." },
    intro:
      "Conjuntos de dados publicados por instituições e operadores portugueses, recolhidos onde são publicados e servidos num formato único e coerente. De utilização gratuita, sem chave e sem conta. Cada conjunto de dados indica quem o publica e tem uma ligação para a origem.",
    searchPlaceholder: "Pesquisar dados: metro, preços dos combustíveis, população…",
    searchLabel: "Pesquisar conjuntos de dados",
    search: "Pesquisar",
    browse: "Ver o catálogo completo",
    useApi: "Usar a API",
    connectAssistant: "Ligar um assistente de IA",
    pressBefore: "ou carregue em",
    pressAfter: "em qualquer página",
    liveLabel: "Recolhido nos últimos minutos",
    rightNow: "Agora mesmo",
    checking: "A verificar a recolha…",
    everythingCollecting: "Tudo a ser recolhido",
    sourcesNotCollecting: (count: number) => `${plural(count, "fonte", "fontes")} sem recolha`,
    loadingLive: "A carregar dados em direto…",
    atAGlance: "Em resumo",
    fromPublishers: (count: number) => `de ${LISTINGS.publishers(count)}`,
    publishers: "Entidades publicadoras",
    institutionsAndOperators: "instituições e operadores",
    nearRealTime: "Quase em tempo real",
    severalTimesAnHour: "recolhidos várias vezes por hora",
    collection: "Recolha",
    allCollecting: "Tudo a recolher",
    notCollecting: (count: number) => `${fmt.int(count)} sem recolha`,
    everythingCollected: "tudo está a ser recolhido",
    seeStatus: "veja a página de estado",
    topicsEyebrow: "Temas",
    topicsTitle: "Explorar por tema",
    recentEyebrow: "Atualizados recentemente",
    recentTitle: "Novidades das entidades publicadoras",
    recentIntro: "Tabelas e séries cuja entidade publicadora divulgou dados novos ou alterados há menos tempo. O que muda várias vezes por hora está no topo desta página.",
    publishersTitle: "De onde vêm os dados",
    allPublishers: "Todas as entidades publicadoras",
    loading: "A carregar",
  },
});
