import type { ReactNode } from "react";
import { plural } from "../lib/format";
import { inLocale } from "../lib/locale";

/** The operations page, its live activity log, and the words every list of runs and feeds uses. */
export const OPERATIONS = inLocale({
  en: {
    /** A feed's health, the word behind its badge. */
    health: {
      Paused: "Paused",
      Collecting: "Collecting",
      "Never succeeded": "Never succeeded",
      "Never run": "Never run",
      Stale: "Stale",
      Retrying: "Retrying",
      Healthy: "Healthy",
    },
    retrying: (failures: number) => `Retrying (${failures})`,
    /** A run's outcome. */
    runStatus: { queued: "Queued", running: "Running", unchanged: "Unchanged", succeeded: "Published", failed: "Failed" },
    trigger: { manual: "manual", history: "history", schedule: "schedule" },
    sourceUnchanged: "Source unchanged",
    rows: (count: number) => plural(count, "row"),
    changes: (count: number) => plural(count, "change"),
    dataThrough: (time: string) => `data through ${time}`,
    copied: "Copied",
    copy: (label: string | undefined) => `Copy ${label ?? "command"}`,
    /* The live log and a past day. */
    waiting: "Waiting for the next run…",
    columns: {
      time: "Time (UTC)",
      status: "Status",
      feed: "Feed",
      trigger: "Trigger",
      rows: "Rows",
      changes: "Changes",
      outcome: "Outcome",
      cadence: "Cadence",
      lastSuccess: "Last success",
      nextRun: "Next run",
      products: "Products",
      requested: "Requested",
      took: "Took",
      observed: "Observed",
      completeness: "Completeness",
    },
    readingDay: (day: string) => `Reading ${day}…`,
    nothingRan: (day: string) => `Nothing ran on ${day}, or the activity record no longer reaches back to it.`,
    runsOn: (count: number, day: string) => `${plural(count, "run")} on ${day} (UTC). Recent runs are hidden while you look back.`,
    onlyLatest: (count: string) => ` Only the latest ${count} are listed.`,
    incompleteDay: " The activity record does not reach back to the start of that day, so its earliest runs are missing.",
    couldNotReadDay: "Could not read that day.",
    runsOnLabel: (day: string) => `Runs on ${day}`,
    filterRuns: "Filter by feed, status or error…",
    collectionFailed: (feed: string) => `${feed}: collection failed`,
    activityEyebrow: "Activity",
    activityTitle: "Every run, as it happens",
    activityBody: "The newest runs across every feed, refreshed every half minute, failures included. Pick a day to see every run from it.",
    pastDayGroup: "Look at a past day",
    showPastDay: "Show a past day",
    backToRecent: "Back to recent",
    latestRuns: (count: number) => `Latest ${count} runs`,
    updated: "updated",
    refreshLatest: "Refresh the latest runs",
    latestWhat: "the latest runs",
    loadingLatest: "Loading the latest runs…",
    /* The operations page. */
    sections: { activity: "Activity", feeds: "Feeds", acquisitions: "Acquisitions" },
    moreProducts: (count: number) => plural(count, "more product", "more products"),
    paused: "paused",
    feedsEyebrow: "Feeds",
    feedsTitle: "What is being collected",
    feedsBody: "Every collection job, the publisher it reads from, how often it runs and how it is doing. Each feed publishes one or more products.",
    feedsByStatus: "Feeds by status",
    loadingFeeds: "Loading feeds…",
    feedsLabel: "Feeds",
    filterFeeds: "Filter by feed, publisher, status…",
    noFeeds: "No feeds yet. Feeds install themselves within minutes of a deploy.",
    allFeeds: "All feeds",
    acquisitionsEyebrow: "Acquisitions",
    acquisitionsTitle: "Every attempt, including the failed ones",
    acquisitionsBody: "The newest hundred attempts the runners made, of every feed or of one. Sort by how long one took, or filter for the failures.",
    runsWhat: "the runs",
    acquisitionsLabel: "Acquisitions",
    filterAcquisitions: "Filter by feed, status, error…",
    loadingAcquisitions: "Loading acquisitions…",
    noRuns: "No runs yet. Collection starts within minutes of a deploy.",
    filterByFeed: "Filter by feed",
    refresh: "Refresh",
    eyebrow: "Operations",
    title: "Every feed, every attempt.",
    intro: (statusPage: ReactNode) => (
      <>
        Nobody starts or stops anything: feeds install themselves, collect on their own cadence, and retry by themselves when something breaks. This page shows what each feed
        collects and what every run produced. The {statusPage} shows collection hour by hour over the last three days.
      </>
    ),
    statusPage: "status page",
    onThisPage: "On this page",
    feedsWhat: "the feeds",
  },
  pt: {
    health: {
      Paused: "Em pausa",
      Collecting: "A recolher",
      "Never succeeded": "Nunca teve êxito",
      "Never run": "Ainda sem recolhas",
      Stale: "Atrasada",
      Retrying: "A tentar de novo",
      Healthy: "Saudável",
    },
    retrying: (failures: number) => `A tentar de novo (${failures})`,
    runStatus: { queued: "Em fila", running: "A decorrer", unchanged: "Sem alterações", succeeded: "Publicada", failed: "Falhou" },
    trigger: { manual: "manual", history: "histórico", schedule: "agendada" },
    sourceUnchanged: "Origem sem alterações",
    rows: (count: number) => plural(count, "linha"),
    changes: (count: number) => plural(count, "alteração", "alterações"),
    dataThrough: (time: string) => `dados até ${time}`,
    copied: "Copiado",
    copy: (label: string | undefined) => (label ? `Copiar: ${label}` : "Copiar o comando"),
    waiting: "À espera da próxima recolha…",
    columns: {
      time: "Hora (UTC)",
      status: "Estado",
      feed: "Fonte",
      trigger: "Tipo",
      rows: "Linhas",
      changes: "Alterações",
      outcome: "Resultado",
      cadence: "Frequência",
      lastSuccess: "Último êxito",
      nextRun: "Próxima recolha",
      products: "Conjuntos de dados",
      requested: "Pedida",
      took: "Duração",
      observed: "Observada",
      completeness: "Integralidade",
    },
    readingDay: (day: string) => `A ler ${day}…`,
    nothingRan: (day: string) => `Nada correu em ${day}, ou o registo de atividade já não chega tão atrás.`,
    runsOn: (count: number, day: string) => `${plural(count, "recolha")} em ${day} (UTC). As recolhas recentes ficam escondidas enquanto olha para trás.`,
    onlyLatest: (count: string) => ` Só são listadas as ${count} mais recentes.`,
    incompleteDay: " O registo de atividade não chega ao início desse dia, por isso faltam as primeiras recolhas.",
    couldNotReadDay: "Não foi possível ler esse dia.",
    runsOnLabel: (day: string) => `Recolhas em ${day}`,
    filterRuns: "Filtrar por fonte, estado ou erro…",
    collectionFailed: (feed: string) => `${feed}: a recolha falhou`,
    activityEyebrow: "Atividade",
    activityTitle: "Todas as recolhas, à medida que acontecem",
    activityBody: "As recolhas mais recentes de todas as fontes, atualizadas a cada meio minuto, falhas incluídas. Escolha um dia para ver todas as recolhas desse dia.",
    pastDayGroup: "Ver um dia anterior",
    showPastDay: "Mostrar um dia anterior",
    backToRecent: "Voltar às recentes",
    latestRuns: (count: number) => `Últimas ${count} recolhas`,
    updated: "atualizado",
    refreshLatest: "Atualizar as últimas recolhas",
    latestWhat: "as últimas recolhas",
    loadingLatest: "A carregar as últimas recolhas…",
    sections: { activity: "Atividade", feeds: "Fontes", acquisitions: "Recolhas" },
    moreProducts: (count: number) => `mais ${plural(count, "conjunto de dados", "conjuntos de dados")}`,
    paused: "em pausa",
    feedsEyebrow: "Fontes",
    feedsTitle: "O que está a ser recolhido",
    feedsBody: "Cada tarefa de recolha, a entidade publicadora de onde lê, com que frequência é executada e em que estado está. Cada fonte publica um ou mais conjuntos de dados.",
    feedsByStatus: "Fontes por estado",
    loadingFeeds: "A carregar as fontes…",
    feedsLabel: "Fontes",
    filterFeeds: "Filtrar por fonte, entidade, estado…",
    noFeeds: "Ainda não há fontes. As fontes instalam-se sozinhas minutos depois de uma implementação.",
    allFeeds: "Todas as fontes",
    acquisitionsEyebrow: "Recolhas",
    acquisitionsTitle: "Todas as tentativas, incluindo as que falharam",
    acquisitionsBody: "As cem tentativas mais recentes, de todas as fontes ou de uma só. Ordene pela duração ou filtre as que falharam.",
    runsWhat: "as recolhas",
    acquisitionsLabel: "Recolhas",
    filterAcquisitions: "Filtrar por fonte, estado, erro…",
    loadingAcquisitions: "A carregar as recolhas…",
    noRuns: "Ainda não há recolhas. A recolha começa minutos depois de uma implementação.",
    filterByFeed: "Filtrar por fonte",
    refresh: "Atualizar",
    eyebrow: "Operações",
    title: "Todas as fontes, todas as tentativas.",
    intro: (statusPage: ReactNode) => (
      <>
        Ninguém inicia nem para nada: as fontes instalam-se sozinhas, recolhem com a sua própria frequência e voltam a tentar sozinhas quando algo falha. Esta página mostra o que
        cada fonte recolhe e o que cada recolha produziu. A {statusPage} mostra a recolha hora a hora nos últimos três dias.
      </>
    ),
    statusPage: "página de estado",
    onThisPage: "Nesta página",
    feedsWhat: "as fontes",
  },
});
