import { inLocale } from "../lib/locale";
import type { AcquisitionStatus } from "../lib/types";

/** One dataset's page: its header, its tabs, the cards beside them and how its current version was built. */
export const PRODUCT = inLocale({
  en: {
    runLabel: { succeeded: "Published", unchanged: "Unchanged", failed: "Failed", running: "Running", queued: "Queued" } satisfies {
      [status in AcquisitionStatus]: string;
    },
    completeness: { partial: "the source returned only part of its data", complete: "the whole source" },
    loading: "Loading…",
    showLess: "Show less",
    showMore: "Show more",
    tabs: { map: "Map", series: "Series", records: "Records", changes: "Changes", corrections: "Corrections", history: "Event history", schema: "Schema", api: "API" },
    notFoundTitle: "Dataset not found · open-data.pt",
    unavailableTitle: "Dataset unavailable · open-data.pt",
    eyebrow: "Dataset",
    noDatasetHere: "No dataset at this address",
    noDatasetChosen: "No dataset chosen",
    nothingNamed: (slug: string) => `Nothing on open-data.pt has the name “${slug}”. The link may be mistyped or out of date: find the dataset in the catalog.`,
    chooseOne: "This page shows one dataset. Choose one from the catalog.",
    openCatalog: "Open the catalog",
    couldNotLoad: "This dataset could not be loaded",
    theDataset: "the dataset",
    catalog: "Catalog",
    emptyAtSource: "Empty at the source",
    version: (version: string) => `version ${version}`,
    checkForUpdates: "Check for updates",
    publishedBy: "Published by",
    reportProblem: "Report a problem",
    views: "Views of this dataset",
    about: "About this dataset",
    whereFrom: "Where it comes from",
    original: "Original",
    shared: "Shared",
    licence: "Licence",
    licenceText: "Text",
    asStated: "As stated by the publisher",
    attribution: "Attribution",
    whatThisIs: "What this is",
    kind: "Kind",
    howCollected: "How it is collected",
    cadence: "Cadence",
    moreOften: "Need it more often?",
    nextRun: "Next run",
    paused: "paused",
    lastCollected: "Last collected",
    history: "History",
    everyChange: "Every change logged",
    latestOnly: "Latest only",
    recentRuns: "Recent runs",
    runsHint: "Newest first. Tap, point at or focus one for its time.",
    catalogEntry: "Catalog entry",
    lineage: "Lineage",
    lineageTitle: "How the current version was built",
    lineageIntro: "From the publisher’s source to what this page serves: when it was read, checked and published.",
    stepSource: "Source",
    sourcePublished: (when: string) => `Source published ${when}`,
    stepRead: "Read",
    earlier: "Earlier",
    notYet: "Not yet",
    rowsRead: (rows: string, changes: string) => `${rows} rows read · ${changes} changes logged`,
    earlierRun: "This version came from an earlier run, no longer in the recent list; newer runs found nothing new.",
    noCollectionYet: "No successful collection yet.",
    stepChecked: "Checked",
    checkedBy: (id: string) => `Checked by ${id}`,
    codeVersion: (version: string) => `code version ${version}`,
    kept: (count: string) => `${count} kept`,
    leftOut: (count: string) => ` · ${count} source rows left out, because they did not pass the checks`,
    checkedEarlier: "Checked by the same earlier run.",
    nothingChecked: "Nothing has been checked yet.",
    stepPublished: "Published",
    versionRows: (version: string, rows: string, series: boolean) => `version ${version} · ${rows} ${series ? "points" : "records"}`,
    dataThrough: (when: string) => `data through ${when}`,
    staleAfter: (span: string) => `stale after ${span} without a refresh`,
  },
  pt: {
    runLabel: { succeeded: "Publicada", unchanged: "Sem alterações", failed: "Falhou", running: "A decorrer", queued: "Em fila" } satisfies {
      [status in AcquisitionStatus]: string;
    },
    completeness: { partial: "a origem devolveu só parte dos dados", complete: "a origem completa" },
    loading: "A carregar…",
    showLess: "Mostrar menos",
    showMore: "Mostrar mais",
    tabs: {
      map: "Mapa",
      series: "Séries",
      records: "Registos",
      changes: "Alterações",
      corrections: "Correções",
      history: "Histórico de eventos",
      schema: "Esquema",
      api: "API",
    },
    notFoundTitle: "Conjunto de dados não encontrado · open-data.pt",
    unavailableTitle: "Conjunto de dados indisponível · open-data.pt",
    eyebrow: "Conjunto de dados",
    noDatasetHere: "Nenhum conjunto de dados neste endereço",
    noDatasetChosen: "Nenhum conjunto de dados escolhido",
    nothingNamed: (slug: string) => `Nada no open-data.pt tem o nome “${slug}”. A ligação pode ter um erro ou estar desatualizada: procure o conjunto de dados no catálogo.`,
    chooseOne: "Esta página mostra um conjunto de dados. Escolha um no catálogo.",
    openCatalog: "Abrir o catálogo",
    couldNotLoad: "Não foi possível carregar este conjunto de dados",
    theDataset: "o conjunto de dados",
    catalog: "Catálogo",
    emptyAtSource: "Vazio na origem",
    version: (version: string) => `versão ${version}`,
    checkForUpdates: "Procurar atualizações",
    publishedBy: "Publicado por",
    reportProblem: "Comunicar um problema",
    views: "Vistas deste conjunto de dados",
    about: "Sobre este conjunto de dados",
    whereFrom: "De onde vem",
    original: "Original",
    shared: "Partilhado",
    licence: "Licença",
    licenceText: "Texto",
    asStated: "Como declarado pela entidade publicadora",
    attribution: "Atribuição",
    whatThisIs: "O que é",
    kind: "Tipo",
    howCollected: "Como é recolhido",
    cadence: "Frequência",
    moreOften: "Precisa dele mais vezes?",
    nextRun: "Próxima recolha",
    paused: "em pausa",
    lastCollected: "Última recolha",
    history: "Histórico",
    everyChange: "Todas as alterações registadas",
    latestOnly: "Só a versão mais recente",
    recentRuns: "Recolhas recentes",
    runsHint: "As mais recentes primeiro. Toque, aponte ou foque uma para ver a hora.",
    catalogEntry: "Entrada no catálogo",
    lineage: "Linhagem",
    lineageTitle: "Como a versão atual foi construída",
    lineageIntro: "Da origem da entidade publicadora ao que esta página serve: quando foi lido, verificado e publicado.",
    stepSource: "Origem",
    sourcePublished: (when: string) => `Publicado na origem a ${when}`,
    stepRead: "Leitura",
    earlier: "Antes",
    notYet: "Ainda não",
    rowsRead: (rows: string, changes: string) => `${rows} linhas lidas · ${changes} alterações registadas`,
    earlierRun: "Esta versão veio de uma recolha anterior, que já não está na lista recente; as recolhas mais novas não encontraram nada de novo.",
    noCollectionYet: "Ainda não houve nenhuma recolha bem-sucedida.",
    stepChecked: "Verificação",
    checkedBy: (id: string) => `Verificado por ${id}`,
    codeVersion: (version: string) => `versão do código ${version}`,
    kept: (count: string) => `${count} mantidas`,
    leftOut: (count: string) => ` · ${count} linhas da origem deixadas de fora, por não passarem nas verificações`,
    checkedEarlier: "Verificado pela mesma recolha anterior.",
    nothingChecked: "Ainda nada foi verificado.",
    stepPublished: "Publicação",
    versionRows: (version: string, rows: string, series: boolean) => `versão ${version} · ${rows} ${series ? "pontos" : "registos"}`,
    dataThrough: (when: string) => `dados até ${when}`,
    staleAfter: (span: string) => `fica desatualizado após ${span} sem atualização`,
  },
});

/** The API tab: every keyless address for this dataset, and what each returns. */
export const API_VIEW = inLocale({
  en: {
    metadata: "Product metadata",
    metadataText: "Schema, version, freshness, cadence, licence and attribution.",
    currentPoints: "Current points",
    currentPointsText: "The newest points, newest first. Filter with seriesKey, from and to.",
    history: "History",
    historyText: "Every point of a past window from the durable history. Windows span up to 366 days; page with the returned cursor.",
    knownThen: "As known then",
    knownThenText: "The same window as it had been published at knownAt: later corrections are left out.",
    recentCorrections: "Recent corrections",
    recentCorrectionsText: "Points revised after they were first published.",
    windowCorrections: "Corrections in a window",
    windowCorrectionsText: "Every new or corrected point ingested in a past window.",
    currentRecords: "Current records",
    currentRecordsText: "The current rows, paged with a cursor.",
    filteredRecords: "Filtered records",
    filteredRecordsText: (field: string) => `Rows whose ${field} equals VALUE. Repeat where= for up to five fields.`,
    inArea: "Records in an area",
    inAreaText: "Rows inside a bounding box, in degrees.",
    geojsonText: "The current rows as a GeoJSON FeatureCollection.",
    eventHistory: "Event history",
    eventHistoryText: "Events of a past window from the durable history, up to 366 days.",
    eventsThen: "Events as known then",
    eventsThenText: "The same window as it had been published at knownAt.",
    recentChanges: "Recent changes",
    recentChangesText: "Creates, updates, corrections and retractions from the recent window.",
    windowChanges: "Changes in a window",
    windowChangesText: "Every revision ingested in a past window.",
    dcat: "DCAT catalog",
    dcatText: "This product’s dataset entry in the JSON-LD catalog.",
    intro:
      "Open, read-only and keyless. Responses are JSON with CORS enabled; errors use application/problem+json. Requests are rate limited per client and a 429 says when to retry.",
    template: "template",
    open: "Open",
    fromTerminal: "From a terminal:",
    exampleRequest: "Example request",
    reference: "Open the API reference",
    copyAction: "Copy to clipboard",
  },
  pt: {
    metadata: "Metadados do conjunto de dados",
    metadataText: "Esquema, versão, atualidade, frequência, licença e atribuição.",
    currentPoints: "Pontos atuais",
    currentPointsText: "Os pontos mais recentes, primeiro os mais novos. Filtre com seriesKey, from e to.",
    history: "Histórico",
    historyText: "Todos os pontos de um período passado, do histórico duradouro. Cada período vai até 366 dias; pagine com o cursor devolvido.",
    knownThen: "Como se sabia então",
    knownThenText: "O mesmo período tal como estava publicado em knownAt: as correções posteriores ficam de fora.",
    recentCorrections: "Correções recentes",
    recentCorrectionsText: "Pontos revistos depois de publicados pela primeira vez.",
    windowCorrections: "Correções num período",
    windowCorrectionsText: "Todos os pontos novos ou corrigidos recebidos num período passado.",
    currentRecords: "Registos atuais",
    currentRecordsText: "As linhas atuais, paginadas com um cursor.",
    filteredRecords: "Registos filtrados",
    filteredRecordsText: (field: string) => `Linhas em que ${field} é igual a VALUE. Repita where= para até cinco campos.`,
    inArea: "Registos numa área",
    inAreaText: "Linhas dentro de um retângulo, em graus.",
    geojsonText: "As linhas atuais como uma FeatureCollection GeoJSON.",
    eventHistory: "Histórico de eventos",
    eventHistoryText: "Eventos de um período passado, do histórico duradouro, até 366 dias.",
    eventsThen: "Eventos como se sabiam então",
    eventsThenText: "O mesmo período tal como estava publicado em knownAt.",
    recentChanges: "Alterações recentes",
    recentChangesText: "Criações, atualizações, correções e retiradas do período recente.",
    windowChanges: "Alterações num período",
    windowChangesText: "Todas as revisões recebidas num período passado.",
    dcat: "Catálogo DCAT",
    dcatText: "A entrada deste conjunto de dados no catálogo JSON-LD.",
    intro:
      "Aberta, só de leitura e sem chave. As respostas são JSON com CORS ativo; os erros usam application/problem+json. Os pedidos têm um limite por cliente e um 429 diz quando tentar de novo.",
    template: "modelo",
    open: "Abrir",
    fromTerminal: "A partir de um terminal:",
    exampleRequest: "Pedido de exemplo",
    reference: "Abrir a referência da API",
    copyAction: "Copiar para a área de transferência",
  },
});

/** The schema tab, and the words a cell or a series label adds to the source's values. */
export const SCHEMA = inLocale({
  en: {
    intro: (version: number) => `The schema written for version ${version}. Every record also carries a`,
    clocks: "object with its event, validity, source-published, observed and ingested clocks.",
    label: "Schema",
    field: "Field",
    type: "Type",
    nullable: "Nullable",
    unit: "Unit",
    yes: "yes",
    no: "no",
    points: (count: string) => `${count} points`,
    wholeNetwork: "Whole network",
  },
  pt: {
    intro: (version: number) => `O esquema escrito para a versão ${version}. Cada registo traz também um objeto`,
    clocks: "com os relógios do evento, da validade, da publicação na origem, da observação e da receção.",
    label: "Esquema",
    field: "Campo",
    type: "Tipo",
    nullable: "Pode ser nulo",
    unit: "Unidade",
    yes: "sim",
    no: "não",
    points: (count: string) => `${count} pontos`,
    wholeNetwork: "Toda a rede",
  },
});

/** What a spinner says to a screen reader. */
export const LOADING = inLocale({ en: "Loading", pt: "A carregar" });
