import { inLocale } from "../lib/locale";

/** Tables of rows: the shared table, the records tab, a record's dialog and the history tabs. */
export const TABLE = inLocale({
  en: {
    filterRows: "Filter rows…",
    filter: (label: string) => `Filter ${label}`,
    rows: (shown: string | undefined, total: string) => (shown === undefined ? `${total} rows` : `${shown} of ${total} rows`),
    nothingToShow: "Nothing to show.",
    noMatch: "No row matches that filter.",
    showing: (range: string, total: string) => `Showing ${range} of ${total}`,
    pagination: {
      navigation: (label: string) => `${label} pages`,
      firstPage: "First page",
      previousPage: "Previous page",
      nextPage: "Next page",
      lastPage: "Last page",
      pageNumber: "Page number",
      pageSize: "Page size",
    },
  },
  pt: {
    filterRows: "Filtrar linhas…",
    filter: (label: string) => `Filtrar ${label}`,
    rows: (shown: string | undefined, total: string) => (shown === undefined ? `${total} linhas` : `${shown} de ${total} linhas`),
    nothingToShow: "Nada para mostrar.",
    noMatch: "Nenhuma linha corresponde a esse filtro.",
    showing: (range: string, total: string) => `A mostrar ${range} de ${total}`,
    pagination: {
      navigation: (label: string) => `Páginas de ${label}`,
      firstPage: "Primeira página",
      previousPage: "Página anterior",
      nextPage: "Página seguinte",
      lastPage: "Última página",
      pageNumber: "Número da página",
      pageSize: "Tamanho da página",
    },
  },
});

export const RECORDS = inLocale({
  en: {
    loadingAll: (count: string) => `Loading all ${count} records…`,
    loadingFirst: (count: string) => `Loading the first ${count} records…`,
    theRecords: "the records",
    emptyTitle: "Empty at the source",
    emptyText: "The latest collection returned no records. The source is still read on its usual schedule, and records appear here as soon as it lists any.",
    showingFirst: (shown: string, total: string) => `Showing the first ${shown} of ${total} records`,
    onlyThese: (remaining: string) => `Search, sorting, downloads and the summaries cover only these rows until you load the other ${remaining}.`,
    couldNotLoadAll: (message: string) => `Could not load every record (${message}). Select Load all records to try again.`,
    loadAll: (total: string, size: string | undefined) => `Load all ${total} records${size ? ` (about ${size})` : ""}`,
    glance: { min: "min", median: "median", max: "max" },
    fromAll: (count: string) => `From all ${count} records.`,
    fromFirst: (count: string) => `From the first ${count} records only.`,
    tableLabel: (title: string) => `${title} records`,
    footerAll: (count: string) => `All ${count} records`,
    footerFirst: (shown: string, total: string) => `First ${shown} of ${total} records`,
    selectRow: "select a row for every field",
  },
  pt: {
    loadingAll: (count: string) => `A carregar todos os ${count} registos…`,
    loadingFirst: (count: string) => `A carregar os primeiros ${count} registos…`,
    theRecords: "os registos",
    emptyTitle: "Vazio na origem",
    emptyText: "A última recolha não devolveu registos. A origem continua a ser lida com a frequência habitual, e os registos aparecem aqui assim que ela listar algum.",
    showingFirst: (shown: string, total: string) => `A mostrar os primeiros ${shown} de ${total} registos`,
    onlyThese: (remaining: string) => `A pesquisa, a ordenação, as transferências e os resumos abrangem só estas linhas até carregar as outras ${remaining}.`,
    couldNotLoadAll: (message: string) => `Não foi possível carregar todos os registos (${message}). Escolha Carregar todos os registos para tentar de novo.`,
    loadAll: (total: string, size: string | undefined) => `Carregar todos os ${total} registos${size ? ` (cerca de ${size})` : ""}`,
    glance: { min: "mín.", median: "mediana", max: "máx." },
    fromAll: (count: string) => `De todos os ${count} registos.`,
    fromFirst: (count: string) => `Só dos primeiros ${count} registos.`,
    tableLabel: (title: string) => `Registos de ${title}`,
    footerAll: (count: string) => `Todos os ${count} registos`,
    footerFirst: (shown: string, total: string) => `Primeiros ${shown} de ${total} registos`,
    selectRow: "escolha uma linha para ver todos os campos",
  },
});

export const RECORD_DIALOG = inLocale({
  en: {
    clocks: { event: "Event", validFrom: "Valid from", validTo: "Valid to", sourcePublished: "Source published", observed: "Observed", ingested: "Ingested" },
    copied: "Copied",
    copyValue: "Copy this value",
    items: (count: number, formatted: string) => (count === 1 ? "1 item" : `${formatted} items`),
    andMore: (keys: string, more: string) => `${keys} and ${more} more`,
    value: "value",
    record: "Record",
    close: "Close",
    clocksHeading: "Clocks",
    copyJson: "Copy JSON",
  },
  pt: {
    clocks: {
      event: "Evento",
      validFrom: "Válido desde",
      validTo: "Válido até",
      sourcePublished: "Publicado na origem",
      observed: "Observado",
      ingested: "Recebido",
    },
    copied: "Copiado",
    copyValue: "Copiar este valor",
    items: (count: number, formatted: string) => (count === 1 ? "1 elemento" : `${formatted} elementos`),
    andMore: (keys: string, more: string) => `${keys} e mais ${more}`,
    value: "valor",
    record: "Registo",
    close: "Fechar",
    clocksHeading: "Relógios",
    copyJson: "Copiar JSON",
  },
});

export const HISTORY = inLocale({
  en: {
    loading: (what: string) => `Loading ${what}…`,
    operations: new Map([
      ["create", "create"],
      ["baseline", "baseline"],
      ["upsert", "upsert"],
      ["retract", "retract"],
    ]),
    operation: "Operation",
    entity: "Entity",
    eventTime: "Event time",
    validFrom: "Valid from",
    sourcePublished: "Source published",
    observed: "Observed",
    changes: "changes",
    theChanges: "the changes",
    changesLabel: (title: string) => `${title} changes`,
    noChanges: "No changes recorded yet: changes are logged when a record is created, updated, corrected, retracted or deleted between collections.",
    changesFooter: "Every row keeps its own event, validity, source and observation clocks. Select one to read what it wrote.",
    series: "Series",
    value: "Value",
    corrected: "Corrected",
    corrections: "corrections",
    theCorrections: "the corrections",
    correctionsLabel: (title: string) => `${title} corrections`,
    noCorrections: "No corrections: one is logged when a later collection changes a point that was already published.",
    correctionsFooter: "A point that was published and later revised, with the moment the correction arrived.",
    last30Days: "the last 30 days",
    theEventHistory: "the event history",
    eventHistoryLabel: (title: string) => `${title} event history`,
    noEvents: "No events in the last 30 days.",
    eventsFooter: (count: string, complete: boolean | undefined) => `${count} events in the last 30 days · coverage ${complete ? "complete" : "may be incomplete"}`,
    loadMore: "Load more",
  },
  pt: {
    loading: (what: string) => `A carregar ${what}…`,
    operations: new Map([
      ["create", "criação"],
      ["baseline", "base"],
      ["upsert", "atualização"],
      ["retract", "retirada"],
    ]),
    operation: "Operação",
    entity: "Registo",
    eventTime: "Hora do evento",
    validFrom: "Válido desde",
    sourcePublished: "Publicado na origem",
    observed: "Observado",
    changes: "as alterações",
    theChanges: "as alterações",
    changesLabel: (title: string) => `Alterações de ${title}`,
    noChanges: "Ainda não há alterações registadas: uma alteração fica registada quando um registo é criado, atualizado, corrigido, retirado ou apagado entre recolhas.",
    changesFooter: "Cada linha guarda os seus próprios relógios de evento, validade, origem e observação. Escolha uma para ler o que escreveu.",
    series: "Série",
    value: "Valor",
    corrected: "Corrigido",
    corrections: "as correções",
    theCorrections: "as correções",
    correctionsLabel: (title: string) => `Correções de ${title}`,
    noCorrections: "Sem correções: uma fica registada quando uma recolha posterior altera um ponto que já estava publicado.",
    correctionsFooter: "Um ponto que foi publicado e depois revisto, com o momento em que a correção chegou.",
    last30Days: "os últimos 30 dias",
    theEventHistory: "o histórico de eventos",
    eventHistoryLabel: (title: string) => `Histórico de eventos de ${title}`,
    noEvents: "Nenhum evento nos últimos 30 dias.",
    eventsFooter: (count: string, complete: boolean | undefined) => `${count} eventos nos últimos 30 dias · cobertura ${complete ? "completa" : "possivelmente incompleta"}`,
    loadMore: "Carregar mais",
  },
});
