import { inLocale } from "../lib/locale";
import type { SummaryResolution } from "../lib/types";

/** The series tab: the chart, its spans and the tables beside it. */
export const SERIES = inLocale({
  en: {
    presets: { "7d": "7 days", "30d": "30 days", "1y": "1 year", all: "All" },
    resolution: { hour: "Hourly averages", day: "Daily averages, Lisbon days", month: "Monthly averages, Lisbon months" } satisfies {
      [resolution in SummaryResolution]: string;
    },
    points: (count: string) => `${count} points`,
    low: (series: string) => `${series} low`,
    range: (series: string) => `${series} range`,
    series: "Series",
    eventTime: "Event time",
    value: "Value",
    valueIn: (unit: string) => (unit ? `Value (${unit})` : "Value"),
    unit: "Unit",
    observed: "Observed",
    period: "Period",
    average: (unit: string) => (unit ? `Average (${unit})` : "Average"),
    lowest: "Lowest",
    highest: "Highest",
    pointsHeader: "Points",
    loading: "Loading series…",
    theSeries: "the series",
    noPoints: "No points yet",
    noPointsText: "Series points appear after the first successful collection.",
    latestOfLargest: (count: number) => `Latest value of the ${count} largest series`,
    someDrawn: (drawn: number, total: string) => `${drawn} of ${total} series drawn; the table has all of them`,
    hover: "Hover for values",
    spanFailed: (message: string) => `Could not load this span: ${message}`,
    summariesLater: "Summaries appear a day after each day ends; until then the chart shows live points.",
    latestFailed: (message: string) => `Could not load the latest points: ${message}`,
    fromLive: "The last day or two come from live points",
    timeSpan: "Time span",
    live: "Live",
    dates: "Dates…",
    showDates: "Show these dates",
    cancel: "Cancel",
    unitGroup: "Unit",
    noUnit: "No unit",
    loadingShort: "Loading",
    pointsIn: (points: string, series: string) => `${points} points in ${series} series`,
    since: (date: string) => `since ${date}`,
    loadingSpan: "Loading this span…",
    nothingInSpan: "Nothing in this span",
    nothingInSpanText: "No summarised or live points fall between these dates.",
    summaries: (title: string) => `${title} summaries`,
    pointsLabel: (title: string) => `${title} points`,
  },
  pt: {
    presets: { "7d": "7 dias", "30d": "30 dias", "1y": "1 ano", all: "Tudo" },
    resolution: { hour: "Médias por hora", day: "Médias diárias, dias de Lisboa", month: "Médias mensais, meses de Lisboa" } satisfies {
      [resolution in SummaryResolution]: string;
    },
    points: (count: string) => `${count} pontos`,
    low: (series: string) => `${series} mínimo`,
    range: (series: string) => `${series} intervalo`,
    series: "Série",
    eventTime: "Hora do evento",
    value: "Valor",
    valueIn: (unit: string) => (unit ? `Valor (${unit})` : "Valor"),
    unit: "Unidade",
    observed: "Observado",
    period: "Período",
    average: (unit: string) => (unit ? `Média (${unit})` : "Média"),
    lowest: "Mínimo",
    highest: "Máximo",
    pointsHeader: "Pontos",
    loading: "A carregar a série…",
    theSeries: "a série",
    noPoints: "Ainda sem pontos",
    noPointsText: "Os pontos da série aparecem depois da primeira recolha bem-sucedida.",
    latestOfLargest: (count: number) => `Último valor das ${count} séries maiores`,
    someDrawn: (drawn: number, total: string) => `${drawn} de ${total} séries desenhadas; a tabela tem todas`,
    hover: "Passe o cursor para ver os valores",
    spanFailed: (message: string) => `Não foi possível carregar este período: ${message}`,
    summariesLater: "Os resumos aparecem um dia depois de cada dia acabar; até lá o gráfico mostra os pontos ao vivo.",
    latestFailed: (message: string) => `Não foi possível carregar os pontos mais recentes: ${message}`,
    fromLive: "O último dia ou dois vêm dos pontos ao vivo",
    timeSpan: "Período",
    live: "Ao vivo",
    dates: "Datas…",
    showDates: "Mostrar estas datas",
    cancel: "Cancelar",
    unitGroup: "Unidade",
    noUnit: "Sem unidade",
    loadingShort: "A carregar",
    pointsIn: (points: string, series: string) => `${points} pontos em ${series} séries`,
    since: (date: string) => `desde ${date}`,
    loadingSpan: "A carregar este período…",
    nothingInSpan: "Nada neste período",
    nothingInSpanText: "Nenhum ponto resumido ou ao vivo cai entre estas datas.",
    summaries: (title: string) => `Resumos de ${title}`,
    pointsLabel: (title: string) => `Pontos de ${title}`,
  },
});
