import { inLocale } from "../lib/locale";

/** The header, the menu and the footer every page shares. */
export const SHELL = inLocale({
  en: {
    nav: {
      catalog: "Catalog",
      publishers: "Publishers",
      licences: "Licences",
      status: "Status",
      start: "Start here",
      api: "API",
      contribute: "Contribute",
    },
    skip: "Skip to content",
    openMenu: "Open the menu",
    home: "open-data.pt home",
    primary: "Primary",
    search: "Search",
    searchLabel: "Search datasets, publishers and pages",
    github: "open-data.pt on GitHub",
    sourceOnGithub: "Source code on GitHub",
    otherLanguage: "PT",
    otherLanguageLabel: "Ver em português",
    footer: "open-data.pt · data from its publishers, under their licences",
    acceptableUse: "Acceptable use",
    sourceCode: "Source code",
    operations: "Operations",
    analytics: "Analytics",
    apiReference: "API reference",
    mcpServer: "MCP server",
    dcat: "DCAT catalog",
  },
  pt: {
    nav: {
      catalog: "Catálogo",
      publishers: "Entidades",
      licences: "Licenças",
      status: "Estado",
      start: "Começar",
      api: "API",
      contribute: "Contribuir",
    },
    skip: "Saltar para o conteúdo",
    openMenu: "Abrir o menu",
    home: "Página inicial do open-data.pt",
    primary: "Principal",
    search: "Pesquisar",
    searchLabel: "Pesquisar conjuntos de dados, entidades publicadoras e páginas",
    github: "O open-data.pt no GitHub",
    sourceOnGithub: "Código-fonte no GitHub",
    otherLanguage: "EN",
    otherLanguageLabel: "View in English",
    footer: "open-data.pt · dados das entidades que os publicam, nas licenças delas",
    acceptableUse: "Utilização aceitável",
    sourceCode: "Código-fonte",
    operations: "Operações",
    analytics: "Estatísticas",
    apiReference: "Referência da API",
    mcpServer: "Servidor MCP",
    dcat: "Catálogo DCAT",
  },
});
