import { fmt, plural } from "../lib/format";
import { inLocale } from "../lib/locale";

/** The status page: collection hour by hour over the last few days, and the incidents in it. */
export const STATUS = inLocale({
  en: {
    levels: { ok: "No recorded issues", major: "Partly affected", severe: "All tracked time affected", none: "Not tracked" },
    /** Why an outage happened, as the middle of a sentence: publisher names keep their capitals. */
    causeClause: {
      source: (publisher: string | undefined) => `${publisher ?? "the publisher"}’s service did not answer`,
      collection: () => "collection failed on this site’s side",
      platform: () => "open-data.pt was not running collections",
    },
    causeLabel: { source: "Source unavailable", collection: "Collection error", platform: "Platform paused" },
    noRecord: "no record yet",
    issueFree: (percent: string) => `${percent}% issue-free`,
    hourSpan: (from: string, to: string) => `${from} to ${to}`,
    hourUntracked: "No tracked collection history",
    hourClean: "No recorded collection issues during tracked time",
    hourAffected: (affected: number, tracked: number, longest: string) => `${affected} of ${tracked} tracked sources affected, up to ${longest} in this hour`,
    trackingBegan: "Tracking began during this hour.",
    andMore: (count: number) => `and ${count} more`,
    currentHour: "Current hour, in progress",
    currentHourSuffix: "; current hour in progress",
    barsInstructions: "One bar per hour. Use left and right arrows to inspect hours, Home and End to jump, and Escape to dismiss details.",
    barsLabel: (label: string, uptime: string, hours: number) => `${label}: ${uptime} over ${hours} hourly slots`,
    eyebrow: "Status",
    title: "Is everything being collected?",
    what: "the collection status",
    checking: "Checking collection…",
    trackedSince: (since: string) => `Collection incidents have been recorded since ${since}; earlier hours are not tracked. Updated every minute.`,
    noHistory: "No collection history has been recorded yet.",
    platformEyebrow: "Platform",
    platformTitle: "Collection on open-data.pt",
    platformBody: "Whether this site was running its collections at all. When it stops, nothing updates.",
    collection: "Collection",
    collectionRuns: "Collection runs",
    running: "Running",
    stoppedFor: (duration: string) => `Stopped for ${duration}`,
    sourcesEyebrow: "Sources",
    sourcesTitle: "Each publisher, hour by hour",
    sourcesBody: (days: number) =>
      `One bar per hour across ${days} days, including the current hour in progress. Hours with a recorded collection issue are drawn full height and in warmer colours. These are collection records, not checks of the publishers’ websites. Percentages leave out untracked time.`,
    publisherLink: (name: string) => `${name}’s tables and series`,
    notCollecting: (failing: number, total: number) => `${failing} of ${total} not collecting`,
    collecting: "Collecting",
    overLastDays: (name: string, days: number) => `${name} over the last ${days} days`,
    historyEyebrow: "History",
    historyTitle: "Past incidents",
    lastDays: (days: number) => `The last ${days} days, newest first.`,
    everyRun: "Every run, as it happens",
    stoppedTitle: "Collection seems to have stopped.",
    stoppedDescription: (since: string) => `Nothing has been collected since ${since}. Data already published stays available.`,
    failingTitle: (failing: number, total: number) => `${fmt.int(failing)} of ${fmt.int(total)} sources ${failing === 1 ? "is" : "are"} not being collected right now.`,
    failingDescription: (publishers: string) => `Affected: ${publishers}. Their last published data stays available and collection retries by itself.`,
    allCollected: (count: number) => `All ${fmt.int(count)} sources are being collected.`,
    everyAnswered: "Every source answered its last collection.",
    legendNow: (hours: number) => `Now · ${hours} hourly bars`,
    noIncidents: (days: number) => `No incidents in the last ${days} days.`,
    since: (time: string) => `Since ${time}`,
    span: (from: string, to: string) => `${from} to ${to}`,
    ongoing: (duration: string) => `ongoing, ${duration} so far`,
    allSources: "All sources",
    attempts: (count: number) => plural(count, "attempt"),
    showAll: (count: number) => `Show all ${count} incidents`,
  },
  pt: {
    levels: { ok: "Sem problemas registados", major: "Parcialmente afetado", severe: "Todo o tempo acompanhado afetado", none: "Não acompanhado" },
    // A publisher's name may take "a" or "o", so the sentence names the publisher without it.
    causeClause: {
      source: () => "o serviço da entidade publicadora não respondeu",
      collection: () => "a recolha falhou do lado deste site",
      platform: () => "o open-data.pt não estava a fazer recolhas",
    },
    causeLabel: { source: "Origem indisponível", collection: "Erro de recolha", platform: "Plataforma em pausa" },
    noRecord: "ainda sem registo",
    issueFree: (percent: string) => `${percent}% sem problemas`,
    hourSpan: (from: string, to: string) => `${from} até ${to}`,
    hourUntracked: "Sem histórico de recolha acompanhado",
    hourClean: "Sem problemas de recolha registados no tempo acompanhado",
    hourAffected: (affected: number, tracked: number, longest: string) =>
      `${affected} de ${tracked} ${tracked === 1 ? "fonte acompanhada afetada" : "fontes acompanhadas afetadas"}, até ${longest} nesta hora`,
    trackingBegan: "O acompanhamento começou durante esta hora.",
    andMore: (count: number) => `e mais ${count}`,
    currentHour: "Hora atual, em curso",
    currentHourSuffix: "; hora atual em curso",
    barsInstructions:
      "Uma barra por hora. Use as setas para a esquerda e para a direita para ver cada hora, Home e End para saltar para o início ou o fim, e Escape para fechar os detalhes.",
    barsLabel: (label: string, uptime: string, hours: number) => `${label}: ${uptime} em ${hours} intervalos de uma hora`,
    eyebrow: "Estado",
    title: "Está tudo a ser recolhido?",
    what: "o estado da recolha",
    checking: "A verificar a recolha…",
    trackedSince: (since: string) => `Os incidentes de recolha são registados desde ${since}; as horas anteriores não são acompanhadas. Atualizado a cada minuto.`,
    noHistory: "Ainda não foi registado nenhum histórico de recolha.",
    platformEyebrow: "Plataforma",
    platformTitle: "Recolha no open-data.pt",
    platformBody: "Se este site estava de todo a fazer as suas recolhas. Quando para, nada é atualizado.",
    collection: "Recolha",
    collectionRuns: "Recolhas",
    running: "A funcionar",
    stoppedFor: (duration: string) => `Parado durante ${duration}`,
    sourcesEyebrow: "Fontes",
    sourcesTitle: "Cada entidade publicadora, hora a hora",
    sourcesBody: (days: number) =>
      `Uma barra por hora ao longo de ${days} dias, incluindo a hora atual, ainda em curso. As horas com um problema de recolha registado aparecem com a altura toda e em cores mais quentes. São registos de recolha, não verificações dos sites das entidades publicadoras. As percentagens deixam de fora o tempo não acompanhado.`,
    publisherLink: (name: string) => `Tabelas e séries: ${name}`,
    notCollecting: (failing: number, total: number) => `${failing} de ${total} sem recolha`,
    collecting: "A recolher",
    overLastDays: (name: string, days: number) => `${name} nos últimos ${days} dias`,
    historyEyebrow: "Histórico",
    historyTitle: "Incidentes anteriores",
    lastDays: (days: number) => `Os últimos ${days} dias, os mais recentes primeiro.`,
    everyRun: "Todas as recolhas, à medida que acontecem",
    stoppedTitle: "A recolha parece ter parado.",
    stoppedDescription: (since: string) => `Nada foi recolhido desde ${since}. Os dados já publicados continuam disponíveis.`,
    failingTitle: (failing: number, total: number) =>
      failing === 1
        ? `${fmt.int(failing)} de ${fmt.int(total)} fontes não está a ser recolhida neste momento.`
        : `${fmt.int(failing)} de ${fmt.int(total)} fontes não estão a ser recolhidas neste momento.`,
    failingDescription: (publishers: string) => `Afetadas: ${publishers}. Os últimos dados publicados continuam disponíveis e a recolha volta a tentar sozinha.`,
    allCollected: (count: number) => `Todas as ${fmt.int(count)} fontes estão a ser recolhidas.`,
    everyAnswered: "Todas as fontes responderam à última recolha.",
    legendNow: (hours: number) => `Agora · ${hours} barras horárias`,
    noIncidents: (days: number) => `Sem incidentes nos últimos ${days} dias.`,
    since: (time: string) => `Desde as ${time}`,
    span: (from: string, to: string) => `Das ${from} às ${to}`,
    ongoing: (duration: string) => `em curso, ${duration} até agora`,
    allSources: "Todas as fontes",
    attempts: (count: number) => plural(count, "tentativa"),
    showAll: (count: number) => `Mostrar os ${count} incidentes`,
  },
});
