// Generated by `pnpm packages:sync` from the arcgis library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { ARCGIS_DEPLOYMENT, ARCGIS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/arcgis";

export default libraryGatekeeper<Env>(ARCGIS_DEPLOYMENT, ARCGIS_EXAMPLES);
