// Generated by `pnpm packages:sync` from the ren library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { REN_DEPLOYMENT, REN_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ren";

export default libraryGatekeeper<Env>(REN_DEPLOYMENT, REN_EXAMPLES);
