// Generated by `pnpm packages:sync` from the metrolisboa library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { METROLISBOA_DEPLOYMENT, METRO_LISBOA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/metrolisboa";

export default libraryGatekeeper<Env>(METROLISBOA_DEPLOYMENT, METRO_LISBOA_EXAMPLES);
