// Generated by `pnpm packages:sync` from the feeds whose first topic is society; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { INE_DEPLOYMENT, INE_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ine";
import { OGC_DEPLOYMENT, OGC_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/ogc";
import { UDATA_DEPLOYMENT, UDATA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/udata";

export default topicGatekeeper<Env>("society", [INE_DEPLOYMENT, OGC_DEPLOYMENT, UDATA_DEPLOYMENT], [...INE_EXAMPLES, ...OGC_EXAMPLES, ...UDATA_EXAMPLES]);
