// Generated by `pnpm packages:sync` from the carris library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { CARRIS_DEPLOYMENT, CARRIS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/carris";

export default libraryGatekeeper<Env>(CARRIS_DEPLOYMENT, CARRIS_EXAMPLES);
