// Generated by `pnpm packages:sync` from the feeds whose first topic is cities; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { ARCGIS_DEPLOYMENT, ARCGIS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/arcgis";
import { CKAN_DEPLOYMENT, CKAN_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/ckan";
import { UDATA_DEPLOYMENT, UDATA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/udata";

export default topicGatekeeper<Env>("cities", [ARCGIS_DEPLOYMENT, CKAN_DEPLOYMENT, UDATA_DEPLOYMENT], [...ARCGIS_EXAMPLES, ...CKAN_EXAMPLES, ...UDATA_EXAMPLES]);
