// Generated by `pnpm packages:sync` from the dgeg library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { DGEG_DEPLOYMENT, DGEG_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/dgeg";

export default libraryGatekeeper<Env>(DGEG_DEPLOYMENT, DGEG_EXAMPLES);
