// Generated by `pnpm packages:sync` from the feeds whose first topic is telecom; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { INE_DEPLOYMENT, INE_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ine";
import { PEERINGDB_DEPLOYMENT } from "@open-data-pt/gatekeeper-shared/sources/peeringdb";
import { RIPESTAT_DEPLOYMENT } from "@open-data-pt/gatekeeper-shared/sources/ripestat";

// Wired but not installed until packages/gatekeeper-shared/src/publication-holds.json clears them: peeringdb, ripestat.
export default topicGatekeeper<Env>("telecom", [INE_DEPLOYMENT, PEERINGDB_DEPLOYMENT, RIPESTAT_DEPLOYMENT], [...INE_EXAMPLES]);
