// Generated by `pnpm packages:sync` from the ckan library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { CKAN_DEPLOYMENT, CKAN_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/ckan";

export default libraryGatekeeper<Env>(CKAN_DEPLOYMENT, CKAN_EXAMPLES);
