// Generated by `pnpm packages:sync` from the feeds whose first topic is environment; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { ARCGIS_DEPLOYMENT, ARCGIS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/arcgis";
import { IPMA_DEPLOYMENT, IPMA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ipma";
import { OGC_DEPLOYMENT, OGC_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/ogc";

export default topicGatekeeper<Env>("environment", [ARCGIS_DEPLOYMENT, IPMA_DEPLOYMENT, OGC_DEPLOYMENT], [...ARCGIS_EXAMPLES, ...IPMA_EXAMPLES, ...OGC_EXAMPLES]);
