// Generated by `pnpm packages:sync` from the ipma library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { IPMA_DEPLOYMENT, IPMA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ipma";

export default libraryGatekeeper<Env>(IPMA_DEPLOYMENT, IPMA_EXAMPLES);
