// Generated by `pnpm packages:sync` from the omie library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { OMIE_DEPLOYMENT, OMIE_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/omie";

export default libraryGatekeeper<Env>(OMIE_DEPLOYMENT, OMIE_EXAMPLES);
