// Generated by `pnpm catalog` from the folders under src/publishers. Do not edit it by hand: add a folder and run it.
import type { PublisherDefinition } from "#/catalog/define";
import { PUBLISHER as agif } from "#/publishers/agif/index";
import { PUBLISHER as anepc } from "#/publishers/anepc/index";
import { PUBLISHER as apa } from "#/publishers/apa/index";
import { PUBLISHER as arquivo_pt } from "#/publishers/arquivo-pt/index";
import { PUBLISHER as arte } from "#/publishers/arte/index";
import { PUBLISHER as assembleia_da_republica } from "#/publishers/assembleia-da-republica/index";
import { PUBLISHER as banco_de_portugal } from "#/publishers/banco-de-portugal/index";
import { PUBLISHER as barraqueiro_oeste } from "#/publishers/barraqueiro-oeste/index";
import { PUBLISHER as bird } from "#/publishers/bird/index";
import { PUBLISHER as boa_viagem } from "#/publishers/boa-viagem/index";
import { PUBLISHER as bora } from "#/publishers/bora/index";
import { PUBLISHER as cada } from "#/publishers/cada/index";
import { PUBLISHER as carris_metropolitana } from "#/publishers/carris-metropolitana/index";
import { PUBLISHER as cm_agueda } from "#/publishers/cm-agueda/index";
import { PUBLISHER as cm_cadaval } from "#/publishers/cm-cadaval/index";
import { PUBLISHER as cm_cascais } from "#/publishers/cm-cascais/index";
import { PUBLISHER as cm_lisboa } from "#/publishers/cm-lisboa/index";
import { PUBLISHER as cm_mafra } from "#/publishers/cm-mafra/index";
import { PUBLISHER as cm_oeiras } from "#/publishers/cm-oeiras/index";
import { PUBLISHER as cm_porto } from "#/publishers/cm-porto/index";
import { PUBLISHER as cp } from "#/publishers/cp/index";
import { PUBLISHER as demarca_design } from "#/publishers/demarca-design/index";
import { PUBLISHER as dgeg } from "#/publishers/dgeg/index";
import { PUBLISHER as dglab } from "#/publishers/dglab/index";
import { PUBLISHER as dgpj } from "#/publishers/dgpj/index";
import { PUBLISHER as dgs } from "#/publishers/dgs/index";
import { PUBLISHER as dgt } from "#/publishers/dgt/index";
import { PUBLISHER as e_redes } from "#/publishers/e-redes/index";
import { PUBLISHER as effis_jrc } from "#/publishers/effis-jrc/index";
import { PUBLISHER as eurostat } from "#/publishers/eurostat/index";
import { PUBLISHER as fertagus } from "#/publishers/fertagus/index";
import { PUBLISHER as horarios_do_funchal } from "#/publishers/horarios-do-funchal/index";
import { PUBLISHER as impic } from "#/publishers/impic/index";
import { PUBLISHER as ine } from "#/publishers/ine/index";
import { PUBLISHER as ioda } from "#/publishers/ioda/index";
import { PUBLISHER as ipma } from "#/publishers/ipma/index";
import { PUBLISHER as lneg } from "#/publishers/lneg/index";
import { PUBLISHER as mare } from "#/publishers/mare/index";
import { PUBLISHER as metro_do_porto } from "#/publishers/metro-do-porto/index";
import { PUBLISHER as metropolitano_de_lisboa } from "#/publishers/metropolitano-de-lisboa/index";
import { PUBLISHER as nasa_firms } from "#/publishers/nasa-firms/index";
import { PUBLISHER as nasa_power } from "#/publishers/nasa-power/index";
import { PUBLISHER as omie } from "#/publishers/omie/index";
import { PUBLISHER as peeringdb } from "#/publishers/peeringdb/index";
import { PUBLISHER as porto_digital } from "#/publishers/porto-digital/index";
import { PUBLISHER as ren } from "#/publishers/ren/index";
import { PUBLISHER as ribatejana } from "#/publishers/ribatejana/index";
import { PUBLISHER as ripe_ncc } from "#/publishers/ripe-ncc/index";
import { PUBLISHER as sns_transparencia } from "#/publishers/sns-transparencia/index";
import { PUBLISHER as stcp } from "#/publishers/stcp/index";
import { PUBLISHER as tcb } from "#/publishers/tcb/index";
import { PUBLISHER as tub_braga } from "#/publishers/tub-braga/index";
import { PUBLISHER as tubabike } from "#/publishers/tubabike/index";
import { PUBLISHER as usgs } from "#/publishers/usgs/index";

/** One publisher folder: its key, and what its `index.ts` declares, feeds and all. */
export interface PublisherFolder {
  id: string;
  publisher: PublisherDefinition;
}

export const PUBLISHER_FOLDERS: readonly PublisherFolder[] = [
  { id: "agif", publisher: agif },
  { id: "anepc", publisher: anepc },
  { id: "apa", publisher: apa },
  { id: "arquivo-pt", publisher: arquivo_pt },
  { id: "arte", publisher: arte },
  { id: "assembleia-da-republica", publisher: assembleia_da_republica },
  { id: "banco-de-portugal", publisher: banco_de_portugal },
  { id: "barraqueiro-oeste", publisher: barraqueiro_oeste },
  { id: "bird", publisher: bird },
  { id: "boa-viagem", publisher: boa_viagem },
  { id: "bora", publisher: bora },
  { id: "cada", publisher: cada },
  { id: "carris-metropolitana", publisher: carris_metropolitana },
  { id: "cm-agueda", publisher: cm_agueda },
  { id: "cm-cadaval", publisher: cm_cadaval },
  { id: "cm-cascais", publisher: cm_cascais },
  { id: "cm-lisboa", publisher: cm_lisboa },
  { id: "cm-mafra", publisher: cm_mafra },
  { id: "cm-oeiras", publisher: cm_oeiras },
  { id: "cm-porto", publisher: cm_porto },
  { id: "cp", publisher: cp },
  { id: "demarca-design", publisher: demarca_design },
  { id: "dgeg", publisher: dgeg },
  { id: "dglab", publisher: dglab },
  { id: "dgpj", publisher: dgpj },
  { id: "dgs", publisher: dgs },
  { id: "dgt", publisher: dgt },
  { id: "e-redes", publisher: e_redes },
  { id: "effis-jrc", publisher: effis_jrc },
  { id: "eurostat", publisher: eurostat },
  { id: "fertagus", publisher: fertagus },
  { id: "horarios-do-funchal", publisher: horarios_do_funchal },
  { id: "impic", publisher: impic },
  { id: "ine", publisher: ine },
  { id: "ioda", publisher: ioda },
  { id: "ipma", publisher: ipma },
  { id: "lneg", publisher: lneg },
  { id: "mare", publisher: mare },
  { id: "metro-do-porto", publisher: metro_do_porto },
  { id: "metropolitano-de-lisboa", publisher: metropolitano_de_lisboa },
  { id: "nasa-firms", publisher: nasa_firms },
  { id: "nasa-power", publisher: nasa_power },
  { id: "omie", publisher: omie },
  { id: "peeringdb", publisher: peeringdb },
  { id: "porto-digital", publisher: porto_digital },
  { id: "ren", publisher: ren },
  { id: "ribatejana", publisher: ribatejana },
  { id: "ripe-ncc", publisher: ripe_ncc },
  { id: "sns-transparencia", publisher: sns_transparencia },
  { id: "stcp", publisher: stcp },
  { id: "tcb", publisher: tcb },
  { id: "tub-braga", publisher: tub_braga },
  { id: "tubabike", publisher: tubabike },
  { id: "usgs", publisher: usgs },
];
