// Generated by `pnpm catalog` from the folders under src/publishers. Do not edit it by hand: add a folder or a file and run it.
import type { DatasetDefinition, PublisherDefinition } from "./define";
import { PUBLISHER as p_agif } from "../publishers/agif";
import { DATASET as d_agif__sgifr_apps_aveiro } from "../publishers/agif/datasets/sgifr-apps-aveiro";
import { DATASET as d_agif__sgifr_apps_beja } from "../publishers/agif/datasets/sgifr-apps-beja";
import { DATASET as d_agif__sgifr_apps_braga } from "../publishers/agif/datasets/sgifr-apps-braga";
import { DATASET as d_agif__sgifr_apps_leiria } from "../publishers/agif/datasets/sgifr-apps-leiria";
import { DATASET as d_agif__sgifr_apps_lisboa } from "../publishers/agif/datasets/sgifr-apps-lisboa";
import { DATASET as d_agif__sgifr_apps_porto } from "../publishers/agif/datasets/sgifr-apps-porto";
import { DATASET as d_agif__sgifr_apps_setubal } from "../publishers/agif/datasets/sgifr-apps-setubal";
import { DATASET as d_agif__sgifr_apps_viseu } from "../publishers/agif/datasets/sgifr-apps-viseu";
import { PUBLISHER as p_anepc } from "../publishers/anepc";
import { DATASET as d_anepc__active_occurrences } from "../publishers/anepc/datasets/active-occurrences";
import { PUBLISHER as p_apa } from "../publishers/apa";
import { DATASET as d_apa__air_quality_stations } from "../publishers/apa/datasets/air-quality-stations";
import { DATASET as d_apa__bathing_beaches } from "../publishers/apa/datasets/bathing-beaches";
import { DATASET as d_apa__bathing_waters } from "../publishers/apa/datasets/bathing-waters";
import { DATASET as d_apa__emissions_trading_installations } from "../publishers/apa/datasets/emissions-trading-installations";
import { DATASET as d_apa__flood_marks } from "../publishers/apa/datasets/flood-marks";
import { DATASET as d_apa__hydrometric_stations } from "../publishers/apa/datasets/hydrometric-stations";
import { DATASET as d_apa__infoagua_alerts } from "../publishers/apa/datasets/infoagua-alerts";
import { DATASET as d_apa__meteorological_stations } from "../publishers/apa/datasets/meteorological-stations";
import { DATASET as d_apa__radnet_stations } from "../publishers/apa/datasets/radnet-stations";
import { DATASET as d_apa__seveso_establishments } from "../publishers/apa/datasets/seveso-establishments";
import { DATASET as d_apa__snirh_monthly_bulletins } from "../publishers/apa/datasets/snirh-monthly-bulletins";
import { DATASET as d_apa__snirh_station_measurements } from "../publishers/apa/datasets/snirh-station-measurements";
import { PUBLISHER as p_arquivo_pt } from "../publishers/arquivo-pt";
import { DATASET as d_arquivo_pt__portuguese_museums } from "../publishers/arquivo-pt/datasets/portuguese-museums";
import { DATASET as d_arquivo_pt__portuguese_parishes } from "../publishers/arquivo-pt/datasets/portuguese-parishes";
import { PUBLISHER as p_arte } from "../publishers/arte";
import { DATASET as d_arte__municipal_ev_charging } from "../publishers/arte/datasets/municipal-ev-charging";
import { DATASET as d_arte__recognised_startups } from "../publishers/arte/datasets/recognised-startups";
import { PUBLISHER as p_assembleia_da_republica } from "../publishers/assembleia-da-republica";
import { DATASET as d_assembleia_da_republica__xvii_legislature } from "../publishers/assembleia-da-republica/datasets/xvii-legislature";
import { PUBLISHER as p_banco_de_portugal } from "../publishers/banco-de-portugal";
import { DATASET as d_banco_de_portugal__banknotes_issued } from "../publishers/banco-de-portugal/datasets/banknotes-issued";
import { DATASET as d_banco_de_portugal__construction_business_financial_health } from "../publishers/banco-de-portugal/datasets/construction-business-financial-health";
import { DATASET as d_banco_de_portugal__consumer_price_index } from "../publishers/banco-de-portugal/datasets/consumer-price-index";
import { DATASET as d_banco_de_portugal__ecb_policy_rates } from "../publishers/banco-de-portugal/datasets/ecb-policy-rates";
import { DATASET as d_banco_de_portugal__emigrant_deposits_by_region } from "../publishers/banco-de-portugal/datasets/emigrant-deposits-by-region";
import { DATASET as d_banco_de_portugal__employment_and_unemployment } from "../publishers/banco-de-portugal/datasets/employment-and-unemployment";
import { DATASET as d_banco_de_portugal__goods_trade_growth } from "../publishers/banco-de-portugal/datasets/goods-trade-growth";
import { DATASET as d_banco_de_portugal__government_deposit_assets } from "../publishers/banco-de-portugal/datasets/government-deposit-assets";
import { DATASET as d_banco_de_portugal__household_indebtedness } from "../publishers/banco-de-portugal/datasets/household-indebtedness";
import { DATASET as d_banco_de_portugal__housing_loan_reference_rates } from "../publishers/banco-de-portugal/datasets/housing-loan-reference-rates";
import { DATASET as d_banco_de_portugal__new_car_loan_amount_percentiles } from "../publishers/banco-de-portugal/datasets/new-car-loan-amount-percentiles";
import { DATASET as d_banco_de_portugal__overdue_household_borrowers_by_region } from "../publishers/banco-de-portugal/datasets/overdue-household-borrowers-by-region";
import { DATASET as d_banco_de_portugal__payment_system_participants } from "../publishers/banco-de-portugal/datasets/payment-system-participants";
import { DATASET as d_banco_de_portugal__portuguese_treasury_yields } from "../publishers/banco-de-portugal/datasets/portuguese-treasury-yields";
import { PUBLISHER as p_barraqueiro_oeste } from "../publishers/barraqueiro-oeste";
import { DATASET as d_barraqueiro_oeste__network } from "../publishers/barraqueiro-oeste/datasets/network";
import { PUBLISHER as p_bird } from "../publishers/bird";
import { DATASET as d_bird__braga } from "../publishers/bird/datasets/braga";
import { DATASET as d_bird__cascais } from "../publishers/bird/datasets/cascais";
import { DATASET as d_bird__lisbon } from "../publishers/bird/datasets/lisbon";
import { DATASET as d_bird__matosinhos } from "../publishers/bird/datasets/matosinhos";
import { DATASET as d_bird__porto } from "../publishers/bird/datasets/porto";
import { PUBLISHER as p_boa_viagem } from "../publishers/boa-viagem";
import { DATASET as d_boa_viagem__network } from "../publishers/boa-viagem/datasets/network";
import { PUBLISHER as p_bora } from "../publishers/bora";
import { DATASET as d_bora__viseu } from "../publishers/bora/datasets/viseu";
import { PUBLISHER as p_cada } from "../publishers/cada";
import { DATASET as d_cada__opinions_2025 } from "../publishers/cada/datasets/opinions-2025";
import { PUBLISHER as p_carris_metropolitana } from "../publishers/carris-metropolitana";
import { DATASET as d_carris_metropolitana__network } from "../publishers/carris-metropolitana/datasets/network";
import { PUBLISHER as p_cm_agueda } from "../publishers/cm-agueda";
import { DATASET as d_cm_agueda__beagueda_stations } from "../publishers/cm-agueda/datasets/beagueda-stations";
import { DATASET as d_cm_agueda__charging_locations } from "../publishers/cm-agueda/datasets/charging-locations";
import { DATASET as d_cm_agueda__electronics_bins } from "../publishers/cm-agueda/datasets/electronics-bins";
import { DATASET as d_cm_agueda__flood_marks } from "../publishers/cm-agueda/datasets/flood-marks";
import { DATASET as d_cm_agueda__textile_bins } from "../publishers/cm-agueda/datasets/textile-bins";
import { DATASET as d_cm_agueda__waste_bins } from "../publishers/cm-agueda/datasets/waste-bins";
import { DATASET as d_cm_agueda__waste_operators } from "../publishers/cm-agueda/datasets/waste-operators";
import { PUBLISHER as p_cm_cadaval } from "../publishers/cm-cadaval";
import { DATASET as d_cm_cadaval__municipal_waste } from "../publishers/cm-cadaval/datasets/municipal-waste";
import { PUBLISHER as p_cm_cascais } from "../publishers/cm-cascais";
import { DATASET as d_cm_cascais__allotments } from "../publishers/cm-cascais/datasets/allotments";
import { DATASET as d_cm_cascais__beaches } from "../publishers/cm-cascais/datasets/beaches";
import { DATASET as d_cm_cascais__bus_stops } from "../publishers/cm-cascais/datasets/bus-stops";
import { DATASET as d_cm_cascais__commerce_services } from "../publishers/cm-cascais/datasets/commerce-services";
import { DATASET as d_cm_cascais__cultural_venues } from "../publishers/cm-cascais/datasets/cultural-venues";
import { DATASET as d_cm_cascais__cycle_paths } from "../publishers/cm-cascais/datasets/cycle-paths";
import { DATASET as d_cm_cascais__defibrillators } from "../publishers/cm-cascais/datasets/defibrillators";
import { DATASET as d_cm_cascais__drinking_fountains } from "../publishers/cm-cascais/datasets/drinking-fountains";
import { DATASET as d_cm_cascais__fire_infrastructure } from "../publishers/cm-cascais/datasets/fire-infrastructure";
import { DATASET as d_cm_cascais__fire_stations } from "../publishers/cm-cascais/datasets/fire-stations";
import { DATASET as d_cm_cascais__forest_fires } from "../publishers/cm-cascais/datasets/forest-fires";
import { DATASET as d_cm_cascais__green_spaces } from "../publishers/cm-cascais/datasets/green-spaces";
import { DATASET as d_cm_cascais__health_facilities } from "../publishers/cm-cascais/datasets/health-facilities";
import { DATASET as d_cm_cascais__hotels } from "../publishers/cm-cascais/datasets/hotels";
import { DATASET as d_cm_cascais__markets } from "../publishers/cm-cascais/datasets/markets";
import { DATASET as d_cm_cascais__municipal_housing } from "../publishers/cm-cascais/datasets/municipal-housing";
import { DATASET as d_cm_cascais__parking } from "../publishers/cm-cascais/datasets/parking";
import { DATASET as d_cm_cascais__pharmacies } from "../publishers/cm-cascais/datasets/pharmacies";
import { DATASET as d_cm_cascais__playgrounds } from "../publishers/cm-cascais/datasets/playgrounds";
import { DATASET as d_cm_cascais__public_schools } from "../publishers/cm-cascais/datasets/public-schools";
import { DATASET as d_cm_cascais__rental_kiosks } from "../publishers/cm-cascais/datasets/rental-kiosks";
import { DATASET as d_cm_cascais__shared_mobility_stations } from "../publishers/cm-cascais/datasets/shared-mobility-stations";
import { DATASET as d_cm_cascais__social_charter } from "../publishers/cm-cascais/datasets/social-charter";
import { DATASET as d_cm_cascais__sports_facilities } from "../publishers/cm-cascais/datasets/sports-facilities";
import { DATASET as d_cm_cascais__street_trees } from "../publishers/cm-cascais/datasets/street-trees";
import { DATASET as d_cm_cascais__taxi_ranks } from "../publishers/cm-cascais/datasets/taxi-ranks";
import { DATASET as d_cm_cascais__train_stations } from "../publishers/cm-cascais/datasets/train-stations";
import { DATASET as d_cm_cascais__tsunami_meeting_points } from "../publishers/cm-cascais/datasets/tsunami-meeting-points";
import { PUBLISHER as p_cm_lisboa } from "../publishers/cm-lisboa";
import { DATASET as d_cm_lisboa__building_permits } from "../publishers/cm-lisboa/datasets/building-permits";
import { DATASET as d_cm_lisboa__cleaning_depots } from "../publishers/cm-lisboa/datasets/cleaning-depots";
import { DATASET as d_cm_lisboa__ecoilhas_subterraneas } from "../publishers/cm-lisboa/datasets/ecoilhas-subterraneas";
import { DATASET as d_cm_lisboa__fire_stations } from "../publishers/cm-lisboa/datasets/fire-stations";
import { DATASET as d_cm_lisboa__health_centres } from "../publishers/cm-lisboa/datasets/health-centres";
import { DATASET as d_cm_lisboa__hotels } from "../publishers/cm-lisboa/datasets/hotels";
import { DATASET as d_cm_lisboa__libraries_archives } from "../publishers/cm-lisboa/datasets/libraries-archives";
import { DATASET as d_cm_lisboa__lora_network } from "../publishers/cm-lisboa/datasets/lora-network";
import { DATASET as d_cm_lisboa__metro_stations } from "../publishers/cm-lisboa/datasets/metro-stations";
import { DATASET as d_cm_lisboa__micromobility_restrictions } from "../publishers/cm-lisboa/datasets/micromobility-restrictions";
import { DATASET as d_cm_lisboa__museums } from "../publishers/cm-lisboa/datasets/museums";
import { DATASET as d_cm_lisboa__parishes } from "../publishers/cm-lisboa/datasets/parishes";
import { DATASET as d_cm_lisboa__parques_caninos } from "../publishers/cm-lisboa/datasets/parques-caninos";
import { DATASET as d_cm_lisboa__parques_infantis } from "../publishers/cm-lisboa/datasets/parques-infantis";
import { DATASET as d_cm_lisboa__primary_schools } from "../publishers/cm-lisboa/datasets/primary-schools";
import { DATASET as d_cm_lisboa__psp_police_stations } from "../publishers/cm-lisboa/datasets/psp-police-stations";
import { DATASET as d_cm_lisboa__recycling_points } from "../publishers/cm-lisboa/datasets/recycling-points";
import { DATASET as d_cm_lisboa__rede_ciclavel } from "../publishers/cm-lisboa/datasets/rede-ciclavel";
import { DATASET as d_cm_lisboa__signalised_crossings } from "../publishers/cm-lisboa/datasets/signalised-crossings";
import { DATASET as d_cm_lisboa__speed_cameras } from "../publishers/cm-lisboa/datasets/speed-cameras";
import { DATASET as d_cm_lisboa__sports_facilities } from "../publishers/cm-lisboa/datasets/sports-facilities";
import { DATASET as d_cm_lisboa__temporary_occupations } from "../publishers/cm-lisboa/datasets/temporary-occupations";
import { DATASET as d_cm_lisboa__tree_incidents } from "../publishers/cm-lisboa/datasets/tree-incidents";
import { DATASET as d_cm_lisboa__tuk_tuk_parking } from "../publishers/cm-lisboa/datasets/tuk-tuk-parking";
import { DATASET as d_cm_lisboa__urgent_works } from "../publishers/cm-lisboa/datasets/urgent-works";
import { PUBLISHER as p_cm_mafra } from "../publishers/cm-mafra";
import { DATASET as d_cm_mafra__centros_saude } from "../publishers/cm-mafra/datasets/centros-saude";
import { DATASET as d_cm_mafra__ciclovias } from "../publishers/cm-mafra/datasets/ciclovias";
import { DATASET as d_cm_mafra__circuitos_pedestres_btt } from "../publishers/cm-mafra/datasets/circuitos-pedestres-btt";
import { DATASET as d_cm_mafra__ecopontos_contentores } from "../publishers/cm-mafra/datasets/ecopontos-contentores";
import { DATASET as d_cm_mafra__equipamentos_cultura } from "../publishers/cm-mafra/datasets/equipamentos-cultura";
import { DATASET as d_cm_mafra__equipamentos_escolares } from "../publishers/cm-mafra/datasets/equipamentos-escolares";
import { DATASET as d_cm_mafra__equipamentos_sociais } from "../publishers/cm-mafra/datasets/equipamentos-sociais";
import { DATASET as d_cm_mafra__espacos_jogo_recreio } from "../publishers/cm-mafra/datasets/espacos-jogo-recreio";
import { DATASET as d_cm_mafra__espacos_verdes } from "../publishers/cm-mafra/datasets/espacos-verdes";
import { DATASET as d_cm_mafra__estacionamento_bicicletas } from "../publishers/cm-mafra/datasets/estacionamento-bicicletas";
import { DATASET as d_cm_mafra__farmacias } from "../publishers/cm-mafra/datasets/farmacias";
import { DATASET as d_cm_mafra__lugares_mobilidade_reduzida } from "../publishers/cm-mafra/datasets/lugares-mobilidade-reduzida";
import { DATASET as d_cm_mafra__parcometros } from "../publishers/cm-mafra/datasets/parcometros";
import { DATASET as d_cm_mafra__parques_caninos } from "../publishers/cm-mafra/datasets/parques-caninos";
import { DATASET as d_cm_mafra__parques_estacionamento } from "../publishers/cm-mafra/datasets/parques-estacionamento";
import { DATASET as d_cm_mafra__patrimonio_inventario } from "../publishers/cm-mafra/datasets/patrimonio-inventario";
import { DATASET as d_cm_mafra__postos_carregamento } from "../publishers/cm-mafra/datasets/postos-carregamento";
import { DATASET as d_cm_mafra__praias } from "../publishers/cm-mafra/datasets/praias";
import { PUBLISHER as p_cm_oeiras } from "../publishers/cm-oeiras";
import { DATASET as d_cm_oeiras__ciclovias } from "../publishers/cm-oeiras/datasets/ciclovias";
import { DATASET as d_cm_oeiras__colonias_errantes } from "../publishers/cm-oeiras/datasets/colonias-errantes";
import { DATASET as d_cm_oeiras__condicionalismos_via_publica } from "../publishers/cm-oeiras/datasets/condicionalismos-via-publica";
import { DATASET as d_cm_oeiras__docas_bicicletas } from "../publishers/cm-oeiras/datasets/docas-bicicletas";
import { DATASET as d_cm_oeiras__equipamentos_saude } from "../publishers/cm-oeiras/datasets/equipamentos-saude";
import { DATASET as d_cm_oeiras__espacos_verdes } from "../publishers/cm-oeiras/datasets/espacos-verdes";
import { DATASET as d_cm_oeiras__estabelecimentos_desocupados } from "../publishers/cm-oeiras/datasets/estabelecimentos-desocupados";
import { DATASET as d_cm_oeiras__hortas_urbanas } from "../publishers/cm-oeiras/datasets/hortas-urbanas";
import { DATASET as d_cm_oeiras__hourly_environment } from "../publishers/cm-oeiras/datasets/hourly-environment";
import { DATASET as d_cm_oeiras__obras_municipais } from "../publishers/cm-oeiras/datasets/obras-municipais";
import { DATASET as d_cm_oeiras__orcamento_participativo } from "../publishers/cm-oeiras/datasets/orcamento-participativo";
import { DATASET as d_cm_oeiras__parquimetros } from "../publishers/cm-oeiras/datasets/parquimetros";
import { DATASET as d_cm_oeiras__pontos_carregamento } from "../publishers/cm-oeiras/datasets/pontos-carregamento";
import { DATASET as d_cm_oeiras__residuos_indiferenciados } from "../publishers/cm-oeiras/datasets/residuos-indiferenciados";
import { PUBLISHER as p_cm_porto } from "../publishers/cm-porto";
import { DATASET as d_cm_porto__cultural_agenda } from "../publishers/cm-porto/datasets/cultural-agenda";
import { DATASET as d_cm_porto__loading_zones } from "../publishers/cm-porto/datasets/loading-zones";
import { DATASET as d_cm_porto__municipal_parking } from "../publishers/cm-porto/datasets/municipal-parking";
import { DATASET as d_cm_porto__municipal_trees } from "../publishers/cm-porto/datasets/municipal-trees";
import { DATASET as d_cm_porto__shared_micromobility_spots } from "../publishers/cm-porto/datasets/shared-micromobility-spots";
import { PUBLISHER as p_cp } from "../publishers/cp";
import { DATASET as d_cp__gtfs } from "../publishers/cp/datasets/gtfs";
import { PUBLISHER as p_demarca_design } from "../publishers/demarca-design";
import { DATASET as d_demarca_design__municipal_accessibility } from "../publishers/demarca-design/datasets/municipal-accessibility";
import { PUBLISHER as p_dgeg } from "../publishers/dgeg";
import { DATASET as d_dgeg__fuel_prices } from "../publishers/dgeg/datasets/fuel-prices";
import { PUBLISHER as p_dglab } from "../publishers/dglab";
import { DATASET as d_dglab__public_libraries_2024 } from "../publishers/dglab/datasets/public-libraries-2024";
import { PUBLISHER as p_dgpj } from "../publishers/dgpj";
import { DATASET as d_dgpj__justice_facilities } from "../publishers/dgpj/datasets/justice-facilities";
import { PUBLISHER as p_dgs } from "../publishers/dgs";
import { DATASET as d_dgs__primary_care_oral_health_referrals } from "../publishers/dgs/datasets/primary-care-oral-health-referrals";
import { PUBLISHER as p_dgt } from "../publishers/dgt";
import { DATASET as d_dgt__caop_acores_central_oriental_freguesias } from "../publishers/dgt/datasets/caop-acores-central-oriental-freguesias";
import { DATASET as d_dgt__caop_acores_central_oriental_municipios } from "../publishers/dgt/datasets/caop-acores-central-oriental-municipios";
import { DATASET as d_dgt__caop_acores_ocidental_freguesias } from "../publishers/dgt/datasets/caop-acores-ocidental-freguesias";
import { DATASET as d_dgt__caop_acores_ocidental_municipios } from "../publishers/dgt/datasets/caop-acores-ocidental-municipios";
import { DATASET as d_dgt__caop_administrative_areas } from "../publishers/dgt/datasets/caop-administrative-areas";
import { DATASET as d_dgt__caop_madeira_freguesias } from "../publishers/dgt/datasets/caop-madeira-freguesias";
import { DATASET as d_dgt__caop_madeira_municipios } from "../publishers/dgt/datasets/caop-madeira-municipios";
import { DATASET as d_dgt__crus } from "../publishers/dgt/datasets/crus";
import { DATASET as d_dgt__crus_shapes } from "../publishers/dgt/datasets/crus-shapes";
import { DATASET as d_dgt__fototeca_index } from "../publishers/dgt/datasets/fototeca-index";
import { DATASET as d_dgt__rgn_rede_gravimetrica } from "../publishers/dgt/datasets/rgn-rede-gravimetrica";
import { DATASET as d_dgt__rgn_rede_maregrafica } from "../publishers/dgt/datasets/rgn-rede-maregrafica";
import { DATASET as d_dgt__rgn_rede_nivelamento } from "../publishers/dgt/datasets/rgn-rede-nivelamento";
import { DATASET as d_dgt__rgn_renep_estacoes } from "../publishers/dgt/datasets/rgn-renep-estacoes";
import { DATASET as d_dgt__rgn_vertices_geodesicos } from "../publishers/dgt/datasets/rgn-vertices-geodesicos";
import { DATASET as d_dgt__serras_cumes_principais } from "../publishers/dgt/datasets/serras-cumes-principais";
import { DATASET as d_dgt__serras_principais } from "../publishers/dgt/datasets/serras-principais";
import { DATASET as d_dgt__serras_toponimicas } from "../publishers/dgt/datasets/serras-toponimicas";
import { DATASET as d_dgt__sgifr_pontos } from "../publishers/dgt/datasets/sgifr-pontos";
import { DATASET as d_dgt__snit_medidas_preventivas } from "../publishers/dgt/datasets/snit-medidas-preventivas";
import { DATASET as d_dgt__snit_paap } from "../publishers/dgt/datasets/snit-paap";
import { DATASET as d_dgt__snit_paqat } from "../publishers/dgt/datasets/snit-paqat";
import { DATASET as d_dgt__snit_pdm } from "../publishers/dgt/datasets/snit-pdm";
import { DATASET as d_dgt__snit_peap } from "../publishers/dgt/datasets/snit-peap";
import { DATASET as d_dgt__snit_pfn } from "../publishers/dgt/datasets/snit-pfn";
import { DATASET as d_dgt__snit_pgrh } from "../publishers/dgt/datasets/snit-pgrh";
import { DATASET as d_dgt__snit_pgri } from "../publishers/dgt/datasets/snit-pgri";
import { DATASET as d_dgt__snit_piot } from "../publishers/dgt/datasets/snit-piot";
import { DATASET as d_dgt__snit_pna } from "../publishers/dgt/datasets/snit-pna";
import { DATASET as d_dgt__snit_pnpot } from "../publishers/dgt/datasets/snit-pnpot";
import { DATASET as d_dgt__snit_poaap } from "../publishers/dgt/datasets/snit-poaap";
import { DATASET as d_dgt__snit_poap } from "../publishers/dgt/datasets/snit-poap";
import { DATASET as d_dgt__snit_poc } from "../publishers/dgt/datasets/snit-poc";
import { DATASET as d_dgt__snit_pooc } from "../publishers/dgt/datasets/snit-pooc";
import { DATASET as d_dgt__snit_pp } from "../publishers/dgt/datasets/snit-pp";
import { DATASET as d_dgt__snit_prgp } from "../publishers/dgt/datasets/snit-prgp";
import { DATASET as d_dgt__snit_prn } from "../publishers/dgt/datasets/snit-prn";
import { DATASET as d_dgt__snit_prof } from "../publishers/dgt/datasets/snit-prof";
import { DATASET as d_dgt__snit_prot_plano } from "../publishers/dgt/datasets/snit-prot-plano";
import { DATASET as d_dgt__snit_prot_programa } from "../publishers/dgt/datasets/snit-prot-programa";
import { DATASET as d_dgt__snit_pszaer } from "../publishers/dgt/datasets/snit-pszaer";
import { DATASET as d_dgt__snit_pu } from "../publishers/dgt/datasets/snit-pu";
import { DATASET as d_dgt__snit_rede_natura } from "../publishers/dgt/datasets/snit-rede-natura";
import { DATASET as d_dgt__srup_aeronautica } from "../publishers/dgt/datasets/srup-aeronautica";
import { DATASET as d_dgt__srup_albufeiras } from "../publishers/dgt/datasets/srup-albufeiras";
import { DATASET as d_dgt__srup_areas_protegidas } from "../publishers/dgt/datasets/srup-areas-protegidas";
import { DATASET as d_dgt__srup_arvores_interesse_publico_areas } from "../publishers/dgt/datasets/srup-arvores-interesse-publico-areas";
import { DATASET as d_dgt__srup_arvores_interesse_publico_pontos } from "../publishers/dgt/datasets/srup-arvores-interesse-publico-pontos";
import { DATASET as d_dgt__srup_captacoes_aguas_subterraneas } from "../publishers/dgt/datasets/srup-captacoes-aguas-subterraneas";
import { DATASET as d_dgt__srup_defesa_nacional } from "../publishers/dgt/datasets/srup-defesa-nacional";
import { DATASET as d_dgt__srup_defesa_nacional_zonas } from "../publishers/dgt/datasets/srup-defesa-nacional-zonas";
import { DATASET as d_dgt__srup_estacoes_ferroviarias } from "../publishers/dgt/datasets/srup-estacoes-ferroviarias";
import { DATASET as d_dgt__srup_marcos_geodesicos } from "../publishers/dgt/datasets/srup-marcos-geodesicos";
import { DATASET as d_dgt__srup_rede_eletrica } from "../publishers/dgt/datasets/srup-rede-eletrica";
import { DATASET as d_dgt__srup_rede_ferroviaria } from "../publishers/dgt/datasets/srup-rede-ferroviaria";
import { DATASET as d_dgt__srup_rede_natura_zec } from "../publishers/dgt/datasets/srup-rede-natura-zec";
import { DATASET as d_dgt__srup_rede_natura_zpe } from "../publishers/dgt/datasets/srup-rede-natura-zpe";
import { DATASET as d_dgt__srup_rede_rodoviaria } from "../publishers/dgt/datasets/srup-rede-rodoviaria";
import { DATASET as d_dgt__srup_reserva_agricola } from "../publishers/dgt/datasets/srup-reserva-agricola";
import { DATASET as d_dgt__srup_reserva_ecologica_areas } from "../publishers/dgt/datasets/srup-reserva-ecologica-areas";
import { DATASET as d_dgt__srup_reserva_ecologica_linhas } from "../publishers/dgt/datasets/srup-reserva-ecologica-linhas";
import { PUBLISHER as p_e_redes } from "../publishers/e-redes";
import { DATASET as d_e_redes__active_smart_meter_contracts } from "../publishers/e-redes/datasets/active-smart-meter-contracts";
import { DATASET as d_e_redes__consumption_forecast } from "../publishers/e-redes/datasets/consumption-forecast";
import { DATASET as d_e_redes__contracts_by_power_band } from "../publishers/e-redes/datasets/contracts-by-power-band";
import { DATASET as d_e_redes__distribution_injection } from "../publishers/e-redes/datasets/distribution-injection";
import { DATASET as d_e_redes__districts } from "../publishers/e-redes/datasets/districts";
import { DATASET as d_e_redes__energy_communities } from "../publishers/e-redes/datasets/energy-communities";
import { DATASET as d_e_redes__ev_charging_connections } from "../publishers/e-redes/datasets/ev-charging-connections";
import { DATASET as d_e_redes__ev_grid_connection_requests } from "../publishers/e-redes/datasets/ev-grid-connection-requests";
import { DATASET as d_e_redes__grid_reception_capacity } from "../publishers/e-redes/datasets/grid-reception-capacity";
import { DATASET as d_e_redes__hourly_consumption_lisbon_porto_postcodes } from "../publishers/e-redes/datasets/hourly-consumption-lisbon-porto-postcodes";
import { DATASET as d_e_redes__monthly_postal_consumption } from "../publishers/e-redes/datasets/monthly-postal-consumption";
import { DATASET as d_e_redes__municipal_contracted_capacity } from "../publishers/e-redes/datasets/municipal-contracted-capacity";
import { DATASET as d_e_redes__municipal_monthly_consumption } from "../publishers/e-redes/datasets/municipal-monthly-consumption";
import { DATASET as d_e_redes__municipal_street_lighting } from "../publishers/e-redes/datasets/municipal-street-lighting";
import { DATASET as d_e_redes__municipal_tariff_consumption } from "../publishers/e-redes/datasets/municipal-tariff-consumption";
import { DATASET as d_e_redes__municipal_transformer_capacity } from "../publishers/e-redes/datasets/municipal-transformer-capacity";
import { DATASET as d_e_redes__national_consumption } from "../publishers/e-redes/datasets/national-consumption";
import { DATASET as d_e_redes__national_production } from "../publishers/e-redes/datasets/national-production";
import { DATASET as d_e_redes__scheduled_interruptions } from "../publishers/e-redes/datasets/scheduled-interruptions";
import { DATASET as d_e_redes__self_consumption_exported_energy } from "../publishers/e-redes/datasets/self-consumption-exported-energy";
import { DATASET as d_e_redes__self_consumption_installations } from "../publishers/e-redes/datasets/self-consumption-installations";
import { DATASET as d_e_redes__service_continuity } from "../publishers/e-redes/datasets/service-continuity";
import { DATASET as d_e_redes__substation_load } from "../publishers/e-redes/datasets/substation-load";
import { PUBLISHER as p_effis_jrc } from "../publishers/effis-jrc";
import { DATASET as d_effis_jrc__effis_portugal_recent_burnt_areas } from "../publishers/effis-jrc/datasets/effis-portugal-recent-burnt-areas";
import { PUBLISHER as p_eurostat } from "../publishers/eurostat";
import { DATASET as d_eurostat__portugal_economic_sentiment } from "../publishers/eurostat/datasets/portugal-economic-sentiment";
import { DATASET as d_eurostat__portugal_electricity_generation } from "../publishers/eurostat/datasets/portugal-electricity-generation";
import { DATASET as d_eurostat__portugal_hicp_annual_rate } from "../publishers/eurostat/datasets/portugal-hicp-annual-rate";
import { DATASET as d_eurostat__portugal_house_price_index } from "../publishers/eurostat/datasets/portugal-house-price-index";
import { DATASET as d_eurostat__portugal_industrial_production } from "../publishers/eurostat/datasets/portugal-industrial-production";
import { DATASET as d_eurostat__portugal_long_term_interest_rate } from "../publishers/eurostat/datasets/portugal-long-term-interest-rate";
import { DATASET as d_eurostat__portugal_monthly_unemployment } from "../publishers/eurostat/datasets/portugal-monthly-unemployment";
import { DATASET as d_eurostat__portugal_quarterly_gdp } from "../publishers/eurostat/datasets/portugal-quarterly-gdp";
import { DATASET as d_eurostat__portugal_retail_trade_volume } from "../publishers/eurostat/datasets/portugal-retail-trade-volume";
import { DATASET as d_eurostat__portugal_tourism_nights } from "../publishers/eurostat/datasets/portugal-tourism-nights";
import { PUBLISHER as p_fertagus } from "../publishers/fertagus";
import { DATASET as d_fertagus__gtfs } from "../publishers/fertagus/datasets/gtfs";
import { PUBLISHER as p_horarios_do_funchal } from "../publishers/horarios-do-funchal";
import { DATASET as d_horarios_do_funchal__gtfs } from "../publishers/horarios-do-funchal/datasets/gtfs";
import { PUBLISHER as p_impic } from "../publishers/impic";
import { DATASET as d_impic__base_contract_modifications_2026 } from "../publishers/impic/datasets/base-contract-modifications-2026";
import { DATASET as d_impic__base_procurement_entities } from "../publishers/impic/datasets/base-procurement-entities";
import { DATASET as d_impic__base_procurement_notices_2026 } from "../publishers/impic/datasets/base-procurement-notices-2026";
import { PUBLISHER as p_ine } from "../publishers/ine";
import { DATASET as d_ine__airport_passengers_embarked } from "../publishers/ine/datasets/airport-passengers-embarked";
import { DATASET as d_ine__average_monthly_earnings } from "../publishers/ine/datasets/average-monthly-earnings";
import { DATASET as d_ine__broadband_accesses_per_100 } from "../publishers/ine/datasets/broadband-accesses-per-100";
import { DATASET as d_ine__broadband_data_traffic } from "../publishers/ine/datasets/broadband-data-traffic";
import { DATASET as d_ine__consumer_price_index } from "../publishers/ine/datasets/consumer-price-index";
import { DATASET as d_ine__crime_rate } from "../publishers/ine/datasets/crime-rate";
import { DATASET as d_ine__declared_income_per_inhabitant } from "../publishers/ine/datasets/declared-income-per-inhabitant";
import { DATASET as d_ine__employment_rate } from "../publishers/ine/datasets/employment-rate";
import { DATASET as d_ine__fixed_broadband_accesses } from "../publishers/ine/datasets/fixed-broadband-accesses";
import { DATASET as d_ine__fixed_broadband_accesses_per_100 } from "../publishers/ine/datasets/fixed-broadband-accesses-per-100";
import { DATASET as d_ine__fixed_telephone_clients } from "../publishers/ine/datasets/fixed-telephone-clients";
import { DATASET as d_ine__heavy_rail_passengers } from "../publishers/ine/datasets/heavy-rail-passengers";
import { DATASET as d_ine__house_price_index } from "../publishers/ine/datasets/house-price-index";
import { DATASET as d_ine__household_broadband_access } from "../publishers/ine/datasets/household-broadband-access";
import { DATASET as d_ine__household_income_gini } from "../publishers/ine/datasets/household-income-gini";
import { DATASET as d_ine__household_income_p90_p10 } from "../publishers/ine/datasets/household-income-p90-p10";
import { DATASET as d_ine__housing_transactions_value } from "../publishers/ine/datasets/housing-transactions-value";
import { DATASET as d_ine__industrial_production_index } from "../publishers/ine/datasets/industrial-production-index";
import { DATASET as d_ine__live_births } from "../publishers/ine/datasets/live-births";
import { DATASET as d_ine__median_bank_valuation } from "../publishers/ine/datasets/median-bank-valuation";
import { DATASET as d_ine__median_home_sale_price } from "../publishers/ine/datasets/median-home-sale-price";
import { DATASET as d_ine__median_household_income_after_tax } from "../publishers/ine/datasets/median-household-income-after-tax";
import { DATASET as d_ine__resident_population } from "../publishers/ine/datasets/resident-population";
import { DATASET as d_ine__taxpayer_income_distribution } from "../publishers/ine/datasets/taxpayer-income-distribution";
import { DATASET as d_ine__tourism_overnight_stays } from "../publishers/ine/datasets/tourism-overnight-stays";
import { DATASET as d_ine__unemployment_rate } from "../publishers/ine/datasets/unemployment-rate";
import { PUBLISHER as p_ioda } from "../publishers/ioda";
import { DATASET as d_ioda__portugal_internet_outages } from "../publishers/ioda/datasets/portugal-internet-outages";
import { PUBLISHER as p_ipma } from "../publishers/ipma";
import { DATASET as d_ipma__daily_forecast } from "../publishers/ipma/datasets/daily-forecast";
import { DATASET as d_ipma__fire_risk } from "../publishers/ipma/datasets/fire-risk";
import { DATASET as d_ipma__municipal_climate } from "../publishers/ipma/datasets/municipal-climate";
import { DATASET as d_ipma__sea_forecast } from "../publishers/ipma/datasets/sea-forecast";
import { DATASET as d_ipma__seismic } from "../publishers/ipma/datasets/seismic";
import { DATASET as d_ipma__shellfish_restrictions } from "../publishers/ipma/datasets/shellfish-restrictions";
import { DATASET as d_ipma__station_observations } from "../publishers/ipma/datasets/station-observations";
import { DATASET as d_ipma__uv_index } from "../publishers/ipma/datasets/uv-index";
import { DATASET as d_ipma__weather_warnings } from "../publishers/ipma/datasets/weather-warnings";
import { PUBLISHER as p_lneg } from "../publishers/lneg";
import { DATASET as d_lneg__falhas_geologicas } from "../publishers/lneg/datasets/falhas-geologicas";
import { DATASET as d_lneg__ocorrencias_minerais } from "../publishers/lneg/datasets/ocorrencias-minerais";
import { DATASET as d_lneg__pontos_de_agua } from "../publishers/lneg/datasets/pontos-de-agua";
import { DATASET as d_lneg__sistemas_aquiferos } from "../publishers/lneg/datasets/sistemas-aquiferos";
import { DATASET as d_lneg__sondagens } from "../publishers/lneg/datasets/sondagens";
import { PUBLISHER as p_mare } from "../publishers/mare";
import { DATASET as d_mare__network } from "../publishers/mare/datasets/network";
import { PUBLISHER as p_metro_do_porto } from "../publishers/metro-do-porto";
import { DATASET as d_metro_do_porto__gtfs } from "../publishers/metro-do-porto/datasets/gtfs";
import { PUBLISHER as p_metropolitano_de_lisboa } from "../publishers/metropolitano-de-lisboa";
import { DATASET as d_metropolitano_de_lisboa__gtfs } from "../publishers/metropolitano-de-lisboa/datasets/gtfs";
import { DATASET as d_metropolitano_de_lisboa__network } from "../publishers/metropolitano-de-lisboa/datasets/network";
import { PUBLISHER as p_nasa_firms } from "../publishers/nasa-firms";
import { DATASET as d_nasa_firms__portugal_thermal_anomalies } from "../publishers/nasa-firms/datasets/portugal-thermal-anomalies";
import { PUBLISHER as p_nasa_power } from "../publishers/nasa-power";
import { DATASET as d_nasa_power__portugal_solar_resource } from "../publishers/nasa-power/datasets/portugal-solar-resource";
import { PUBLISHER as p_omie } from "../publishers/omie";
import { DATASET as d_omie__day_ahead_prices } from "../publishers/omie/datasets/day-ahead-prices";
import { PUBLISHER as p_peeringdb } from "../publishers/peeringdb";
import { DATASET as d_peeringdb__portugal_exchanges } from "../publishers/peeringdb/datasets/portugal-exchanges";
import { PUBLISHER as p_porto_digital } from "../publishers/porto-digital";
import { DATASET as d_porto_digital__urban_sensors } from "../publishers/porto-digital/datasets/urban-sensors";
import { PUBLISHER as p_ren } from "../publishers/ren";
import { DATASET as d_ren__electricity_system } from "../publishers/ren/datasets/electricity-system";
import { DATASET as d_ren__gas_system } from "../publishers/ren/datasets/gas-system";
import { PUBLISHER as p_ribatejana } from "../publishers/ribatejana";
import { DATASET as d_ribatejana__network } from "../publishers/ribatejana/datasets/network";
import { PUBLISHER as p_ripe_ncc } from "../publishers/ripe-ncc";
import { DATASET as d_ripe_ncc__atlas_portugal } from "../publishers/ripe-ncc/datasets/atlas-portugal";
import { DATASET as d_ripe_ncc__portugal_internet_resources } from "../publishers/ripe-ncc/datasets/portugal-internet-resources";
import { PUBLISHER as p_sns_transparencia } from "../publishers/sns-transparencia";
import { DATASET as d_sns_transparencia__births_and_caesareans } from "../publishers/sns-transparencia/datasets/births-and-caesareans";
import { DATASET as d_sns_transparencia__blood_collection } from "../publishers/sns-transparencia/datasets/blood-collection";
import { DATASET as d_sns_transparencia__cancer_screening } from "../publishers/sns-transparencia/datasets/cancer-screening";
import { DATASET as d_sns_transparencia__continuing_care_waiting } from "../publishers/sns-transparencia/datasets/continuing-care-waiting";
import { DATASET as d_sns_transparencia__daily_death_certificates } from "../publishers/sns-transparencia/datasets/daily-death-certificates";
import { DATASET as d_sns_transparencia__dispensed_medicines } from "../publishers/sns-transparencia/datasets/dispensed-medicines";
import { DATASET as d_sns_transparencia__emergency_calls_transferred_sns24 } from "../publishers/sns-transparencia/datasets/emergency-calls-transferred-sns24";
import { DATASET as d_sns_transparencia__emergency_triage } from "../publishers/sns-transparencia/datasets/emergency-triage";
import { DATASET as d_sns_transparencia__first_consultations_within_target } from "../publishers/sns-transparencia/datasets/first-consultations-within-target";
import { DATASET as d_sns_transparencia__generic_medicine_dispensing } from "../publishers/sns-transparencia/datasets/generic-medicine-dispensing";
import { DATASET as d_sns_transparencia__health_framework_agreements } from "../publishers/sns-transparencia/datasets/health-framework-agreements";
import { DATASET as d_sns_transparencia__health_procurement } from "../publishers/sns-transparencia/datasets/health-procurement";
import { DATASET as d_sns_transparencia__hospital_beds_by_type } from "../publishers/sns-transparencia/datasets/hospital-beds-by-type";
import { DATASET as d_sns_transparencia__hospital_emergency_attendances } from "../publishers/sns-transparencia/datasets/hospital-emergency-attendances";
import { DATASET as d_sns_transparencia__hospital_occupancy } from "../publishers/sns-transparencia/datasets/hospital-occupancy";
import { DATASET as d_sns_transparencia__icaro_heat_index } from "../publishers/sns-transparencia/datasets/icaro-heat-index";
import { DATASET as d_sns_transparencia__inem_dispatches } from "../publishers/sns-transparencia/datasets/inem-dispatches";
import { DATASET as d_sns_transparencia__inem_emergency_calls } from "../publishers/sns-transparencia/datasets/inem-emergency-calls";
import { DATASET as d_sns_transparencia__inem_occurrences_by_priority } from "../publishers/sns-transparencia/datasets/inem-occurrences-by-priority";
import { DATASET as d_sns_transparencia__legionella_environmental_monitoring } from "../publishers/sns-transparencia/datasets/legionella-environmental-monitoring";
import { DATASET as d_sns_transparencia__licensed_public_defibrillator_programmes } from "../publishers/sns-transparencia/datasets/licensed-public-defibrillator-programmes";
import { DATASET as d_sns_transparencia__lvt_hospital_morbidity_mortality } from "../publishers/sns-transparencia/datasets/lvt-hospital-morbidity-mortality";
import { DATASET as d_sns_transparencia__medical_specialty_training_vacancies } from "../publishers/sns-transparencia/datasets/medical-specialty-training-vacancies";
import { DATASET as d_sns_transparencia__medicine_package_prices } from "../publishers/sns-transparencia/datasets/medicine-package-prices";
import { DATASET as d_sns_transparencia__newborn_screening } from "../publishers/sns-transparencia/datasets/newborn-screening";
import { DATASET as d_sns_transparencia__poison_information_calls } from "../publishers/sns-transparencia/datasets/poison-information-calls";
import { DATASET as d_sns_transparencia__pregnancy_line_triage } from "../publishers/sns-transparencia/datasets/pregnancy-line-triage";
import { DATASET as d_sns_transparencia__primary_care_consultation_access } from "../publishers/sns-transparencia/datasets/primary-care-consultation-access";
import { DATASET as d_sns_transparencia__primary_care_flu_consultations } from "../publishers/sns-transparencia/datasets/primary-care-flu-consultations";
import { DATASET as d_sns_transparencia__psychology_consultations } from "../publishers/sns-transparencia/datasets/psychology-consultations";
import { DATASET as d_sns_transparencia__seasonal_flu_vaccination_coverage } from "../publishers/sns-transparencia/datasets/seasonal-flu-vaccination-coverage";
import { DATASET as d_sns_transparencia__sickness_self_declarations } from "../publishers/sns-transparencia/datasets/sickness-self-declarations";
import { DATASET as d_sns_transparencia__supplier_debt_and_arrears } from "../publishers/sns-transparencia/datasets/supplier-debt-and-arrears";
import { DATASET as d_sns_transparencia__surgery_waiting_target } from "../publishers/sns-transparencia/datasets/surgery-waiting-target";
import { PUBLISHER as p_stcp } from "../publishers/stcp";
import { DATASET as d_stcp__gtfs } from "../publishers/stcp/datasets/gtfs";
import { DATASET as d_stcp__porto_stcp_bus_positions } from "../publishers/stcp/datasets/porto-stcp-bus-positions";
import { PUBLISHER as p_tcb } from "../publishers/tcb";
import { DATASET as d_tcb__barreiro_gtfs } from "../publishers/tcb/datasets/barreiro-gtfs";
import { PUBLISHER as p_tub_braga } from "../publishers/tub-braga";
import { DATASET as d_tub_braga__gtfs } from "../publishers/tub-braga/datasets/gtfs";
import { PUBLISHER as p_tubabike } from "../publishers/tubabike";
import { DATASET as d_tubabike__barcelos } from "../publishers/tubabike/datasets/barcelos";
import { PUBLISHER as p_usgs } from "../publishers/usgs";
import { DATASET as d_usgs__portugal_earthquakes } from "../publishers/usgs/datasets/portugal-earthquakes";

/** One publisher folder: its key, what its `index.ts` declares, and every dataset file under it, keyed. */
export interface PublisherFolder {
  id: string;
  publisher: PublisherDefinition;
  datasets: ReadonlyArray<{ id: string; dataset: DatasetDefinition }>;
}

export const PUBLISHER_FOLDERS: readonly PublisherFolder[] = [
  {
    id: "agif",
    publisher: p_agif,
    datasets: [
      { id: "agif-sgifr-apps-aveiro", dataset: d_agif__sgifr_apps_aveiro },
      { id: "agif-sgifr-apps-beja", dataset: d_agif__sgifr_apps_beja },
      { id: "agif-sgifr-apps-braga", dataset: d_agif__sgifr_apps_braga },
      { id: "agif-sgifr-apps-leiria", dataset: d_agif__sgifr_apps_leiria },
      { id: "agif-sgifr-apps-lisboa", dataset: d_agif__sgifr_apps_lisboa },
      { id: "agif-sgifr-apps-porto", dataset: d_agif__sgifr_apps_porto },
      { id: "agif-sgifr-apps-setubal", dataset: d_agif__sgifr_apps_setubal },
      { id: "agif-sgifr-apps-viseu", dataset: d_agif__sgifr_apps_viseu },
    ],
  },
  {
    id: "anepc",
    publisher: p_anepc,
    datasets: [
      { id: "anepc-active-occurrences", dataset: d_anepc__active_occurrences },
    ],
  },
  {
    id: "apa",
    publisher: p_apa,
    datasets: [
      { id: "apa-air-quality-stations", dataset: d_apa__air_quality_stations },
      { id: "apa-bathing-beaches", dataset: d_apa__bathing_beaches },
      { id: "apa-bathing-waters", dataset: d_apa__bathing_waters },
      { id: "apa-emissions-trading-installations", dataset: d_apa__emissions_trading_installations },
      { id: "apa-flood-marks", dataset: d_apa__flood_marks },
      { id: "apa-hydrometric-stations", dataset: d_apa__hydrometric_stations },
      { id: "apa-infoagua-alerts", dataset: d_apa__infoagua_alerts },
      { id: "apa-meteorological-stations", dataset: d_apa__meteorological_stations },
      { id: "apa-radnet-stations", dataset: d_apa__radnet_stations },
      { id: "apa-seveso-establishments", dataset: d_apa__seveso_establishments },
      { id: "apa-snirh-monthly-bulletins", dataset: d_apa__snirh_monthly_bulletins },
      { id: "apa-snirh-station-measurements", dataset: d_apa__snirh_station_measurements },
    ],
  },
  {
    id: "arquivo-pt",
    publisher: p_arquivo_pt,
    datasets: [
      { id: "arquivo-pt-portuguese-museums", dataset: d_arquivo_pt__portuguese_museums },
      { id: "arquivo-pt-portuguese-parishes", dataset: d_arquivo_pt__portuguese_parishes },
    ],
  },
  {
    id: "arte",
    publisher: p_arte,
    datasets: [
      { id: "arte-municipal-ev-charging", dataset: d_arte__municipal_ev_charging },
      { id: "arte-recognised-startups", dataset: d_arte__recognised_startups },
    ],
  },
  {
    id: "assembleia-da-republica",
    publisher: p_assembleia_da_republica,
    datasets: [
      { id: "assembleia-da-republica-xvii-legislature", dataset: d_assembleia_da_republica__xvii_legislature },
    ],
  },
  {
    id: "banco-de-portugal",
    publisher: p_banco_de_portugal,
    datasets: [
      { id: "banco-de-portugal-banknotes-issued", dataset: d_banco_de_portugal__banknotes_issued },
      { id: "banco-de-portugal-construction-business-financial-health", dataset: d_banco_de_portugal__construction_business_financial_health },
      { id: "banco-de-portugal-consumer-price-index", dataset: d_banco_de_portugal__consumer_price_index },
      { id: "banco-de-portugal-ecb-policy-rates", dataset: d_banco_de_portugal__ecb_policy_rates },
      { id: "banco-de-portugal-emigrant-deposits-by-region", dataset: d_banco_de_portugal__emigrant_deposits_by_region },
      { id: "banco-de-portugal-employment-and-unemployment", dataset: d_banco_de_portugal__employment_and_unemployment },
      { id: "banco-de-portugal-goods-trade-growth", dataset: d_banco_de_portugal__goods_trade_growth },
      { id: "banco-de-portugal-government-deposit-assets", dataset: d_banco_de_portugal__government_deposit_assets },
      { id: "banco-de-portugal-household-indebtedness", dataset: d_banco_de_portugal__household_indebtedness },
      { id: "banco-de-portugal-housing-loan-reference-rates", dataset: d_banco_de_portugal__housing_loan_reference_rates },
      { id: "banco-de-portugal-new-car-loan-amount-percentiles", dataset: d_banco_de_portugal__new_car_loan_amount_percentiles },
      { id: "banco-de-portugal-overdue-household-borrowers-by-region", dataset: d_banco_de_portugal__overdue_household_borrowers_by_region },
      { id: "banco-de-portugal-payment-system-participants", dataset: d_banco_de_portugal__payment_system_participants },
      { id: "banco-de-portugal-portuguese-treasury-yields", dataset: d_banco_de_portugal__portuguese_treasury_yields },
    ],
  },
  {
    id: "barraqueiro-oeste",
    publisher: p_barraqueiro_oeste,
    datasets: [
      { id: "barraqueiro-oeste-network", dataset: d_barraqueiro_oeste__network },
    ],
  },
  {
    id: "bird",
    publisher: p_bird,
    datasets: [
      { id: "bird-braga", dataset: d_bird__braga },
      { id: "bird-cascais", dataset: d_bird__cascais },
      { id: "bird-lisbon", dataset: d_bird__lisbon },
      { id: "bird-matosinhos", dataset: d_bird__matosinhos },
      { id: "bird-porto", dataset: d_bird__porto },
    ],
  },
  {
    id: "boa-viagem",
    publisher: p_boa_viagem,
    datasets: [
      { id: "boa-viagem-network", dataset: d_boa_viagem__network },
    ],
  },
  {
    id: "bora",
    publisher: p_bora,
    datasets: [
      { id: "bora-viseu", dataset: d_bora__viseu },
    ],
  },
  {
    id: "cada",
    publisher: p_cada,
    datasets: [
      { id: "cada-opinions-2025", dataset: d_cada__opinions_2025 },
    ],
  },
  {
    id: "carris-metropolitana",
    publisher: p_carris_metropolitana,
    datasets: [
      { id: "carris-metropolitana-network", dataset: d_carris_metropolitana__network },
    ],
  },
  {
    id: "cm-agueda",
    publisher: p_cm_agueda,
    datasets: [
      { id: "cm-agueda-beagueda-stations", dataset: d_cm_agueda__beagueda_stations },
      { id: "cm-agueda-charging-locations", dataset: d_cm_agueda__charging_locations },
      { id: "cm-agueda-electronics-bins", dataset: d_cm_agueda__electronics_bins },
      { id: "cm-agueda-flood-marks", dataset: d_cm_agueda__flood_marks },
      { id: "cm-agueda-textile-bins", dataset: d_cm_agueda__textile_bins },
      { id: "cm-agueda-waste-bins", dataset: d_cm_agueda__waste_bins },
      { id: "cm-agueda-waste-operators", dataset: d_cm_agueda__waste_operators },
    ],
  },
  {
    id: "cm-cadaval",
    publisher: p_cm_cadaval,
    datasets: [
      { id: "cm-cadaval-municipal-waste", dataset: d_cm_cadaval__municipal_waste },
    ],
  },
  {
    id: "cm-cascais",
    publisher: p_cm_cascais,
    datasets: [
      { id: "cm-cascais-allotments", dataset: d_cm_cascais__allotments },
      { id: "cm-cascais-beaches", dataset: d_cm_cascais__beaches },
      { id: "cm-cascais-bus-stops", dataset: d_cm_cascais__bus_stops },
      { id: "cm-cascais-commerce-services", dataset: d_cm_cascais__commerce_services },
      { id: "cm-cascais-cultural-venues", dataset: d_cm_cascais__cultural_venues },
      { id: "cm-cascais-cycle-paths", dataset: d_cm_cascais__cycle_paths },
      { id: "cm-cascais-defibrillators", dataset: d_cm_cascais__defibrillators },
      { id: "cm-cascais-drinking-fountains", dataset: d_cm_cascais__drinking_fountains },
      { id: "cm-cascais-fire-infrastructure", dataset: d_cm_cascais__fire_infrastructure },
      { id: "cm-cascais-fire-stations", dataset: d_cm_cascais__fire_stations },
      { id: "cm-cascais-forest-fires", dataset: d_cm_cascais__forest_fires },
      { id: "cm-cascais-green-spaces", dataset: d_cm_cascais__green_spaces },
      { id: "cm-cascais-health-facilities", dataset: d_cm_cascais__health_facilities },
      { id: "cm-cascais-hotels", dataset: d_cm_cascais__hotels },
      { id: "cm-cascais-markets", dataset: d_cm_cascais__markets },
      { id: "cm-cascais-municipal-housing", dataset: d_cm_cascais__municipal_housing },
      { id: "cm-cascais-parking", dataset: d_cm_cascais__parking },
      { id: "cm-cascais-pharmacies", dataset: d_cm_cascais__pharmacies },
      { id: "cm-cascais-playgrounds", dataset: d_cm_cascais__playgrounds },
      { id: "cm-cascais-public-schools", dataset: d_cm_cascais__public_schools },
      { id: "cm-cascais-rental-kiosks", dataset: d_cm_cascais__rental_kiosks },
      { id: "cm-cascais-shared-mobility-stations", dataset: d_cm_cascais__shared_mobility_stations },
      { id: "cm-cascais-social-charter", dataset: d_cm_cascais__social_charter },
      { id: "cm-cascais-sports-facilities", dataset: d_cm_cascais__sports_facilities },
      { id: "cm-cascais-street-trees", dataset: d_cm_cascais__street_trees },
      { id: "cm-cascais-taxi-ranks", dataset: d_cm_cascais__taxi_ranks },
      { id: "cm-cascais-train-stations", dataset: d_cm_cascais__train_stations },
      { id: "cm-cascais-tsunami-meeting-points", dataset: d_cm_cascais__tsunami_meeting_points },
    ],
  },
  {
    id: "cm-lisboa",
    publisher: p_cm_lisboa,
    datasets: [
      { id: "cm-lisboa-building-permits", dataset: d_cm_lisboa__building_permits },
      { id: "cm-lisboa-cleaning-depots", dataset: d_cm_lisboa__cleaning_depots },
      { id: "cm-lisboa-ecoilhas-subterraneas", dataset: d_cm_lisboa__ecoilhas_subterraneas },
      { id: "cm-lisboa-fire-stations", dataset: d_cm_lisboa__fire_stations },
      { id: "cm-lisboa-health-centres", dataset: d_cm_lisboa__health_centres },
      { id: "cm-lisboa-hotels", dataset: d_cm_lisboa__hotels },
      { id: "cm-lisboa-libraries-archives", dataset: d_cm_lisboa__libraries_archives },
      { id: "cm-lisboa-lora-network", dataset: d_cm_lisboa__lora_network },
      { id: "cm-lisboa-metro-stations", dataset: d_cm_lisboa__metro_stations },
      { id: "cm-lisboa-micromobility-restrictions", dataset: d_cm_lisboa__micromobility_restrictions },
      { id: "cm-lisboa-museums", dataset: d_cm_lisboa__museums },
      { id: "cm-lisboa-parishes", dataset: d_cm_lisboa__parishes },
      { id: "cm-lisboa-parques-caninos", dataset: d_cm_lisboa__parques_caninos },
      { id: "cm-lisboa-parques-infantis", dataset: d_cm_lisboa__parques_infantis },
      { id: "cm-lisboa-primary-schools", dataset: d_cm_lisboa__primary_schools },
      { id: "cm-lisboa-psp-police-stations", dataset: d_cm_lisboa__psp_police_stations },
      { id: "cm-lisboa-recycling-points", dataset: d_cm_lisboa__recycling_points },
      { id: "cm-lisboa-rede-ciclavel", dataset: d_cm_lisboa__rede_ciclavel },
      { id: "cm-lisboa-signalised-crossings", dataset: d_cm_lisboa__signalised_crossings },
      { id: "cm-lisboa-speed-cameras", dataset: d_cm_lisboa__speed_cameras },
      { id: "cm-lisboa-sports-facilities", dataset: d_cm_lisboa__sports_facilities },
      { id: "cm-lisboa-temporary-occupations", dataset: d_cm_lisboa__temporary_occupations },
      { id: "cm-lisboa-tree-incidents", dataset: d_cm_lisboa__tree_incidents },
      { id: "cm-lisboa-tuk-tuk-parking", dataset: d_cm_lisboa__tuk_tuk_parking },
      { id: "cm-lisboa-urgent-works", dataset: d_cm_lisboa__urgent_works },
    ],
  },
  {
    id: "cm-mafra",
    publisher: p_cm_mafra,
    datasets: [
      { id: "cm-mafra-centros-saude", dataset: d_cm_mafra__centros_saude },
      { id: "cm-mafra-ciclovias", dataset: d_cm_mafra__ciclovias },
      { id: "cm-mafra-circuitos-pedestres-btt", dataset: d_cm_mafra__circuitos_pedestres_btt },
      { id: "cm-mafra-ecopontos-contentores", dataset: d_cm_mafra__ecopontos_contentores },
      { id: "cm-mafra-equipamentos-cultura", dataset: d_cm_mafra__equipamentos_cultura },
      { id: "cm-mafra-equipamentos-escolares", dataset: d_cm_mafra__equipamentos_escolares },
      { id: "cm-mafra-equipamentos-sociais", dataset: d_cm_mafra__equipamentos_sociais },
      { id: "cm-mafra-espacos-jogo-recreio", dataset: d_cm_mafra__espacos_jogo_recreio },
      { id: "cm-mafra-espacos-verdes", dataset: d_cm_mafra__espacos_verdes },
      { id: "cm-mafra-estacionamento-bicicletas", dataset: d_cm_mafra__estacionamento_bicicletas },
      { id: "cm-mafra-farmacias", dataset: d_cm_mafra__farmacias },
      { id: "cm-mafra-lugares-mobilidade-reduzida", dataset: d_cm_mafra__lugares_mobilidade_reduzida },
      { id: "cm-mafra-parcometros", dataset: d_cm_mafra__parcometros },
      { id: "cm-mafra-parques-caninos", dataset: d_cm_mafra__parques_caninos },
      { id: "cm-mafra-parques-estacionamento", dataset: d_cm_mafra__parques_estacionamento },
      { id: "cm-mafra-patrimonio-inventario", dataset: d_cm_mafra__patrimonio_inventario },
      { id: "cm-mafra-postos-carregamento", dataset: d_cm_mafra__postos_carregamento },
      { id: "cm-mafra-praias", dataset: d_cm_mafra__praias },
    ],
  },
  {
    id: "cm-oeiras",
    publisher: p_cm_oeiras,
    datasets: [
      { id: "cm-oeiras-ciclovias", dataset: d_cm_oeiras__ciclovias },
      { id: "cm-oeiras-colonias-errantes", dataset: d_cm_oeiras__colonias_errantes },
      { id: "cm-oeiras-condicionalismos-via-publica", dataset: d_cm_oeiras__condicionalismos_via_publica },
      { id: "cm-oeiras-docas-bicicletas", dataset: d_cm_oeiras__docas_bicicletas },
      { id: "cm-oeiras-equipamentos-saude", dataset: d_cm_oeiras__equipamentos_saude },
      { id: "cm-oeiras-espacos-verdes", dataset: d_cm_oeiras__espacos_verdes },
      { id: "cm-oeiras-estabelecimentos-desocupados", dataset: d_cm_oeiras__estabelecimentos_desocupados },
      { id: "cm-oeiras-hortas-urbanas", dataset: d_cm_oeiras__hortas_urbanas },
      { id: "cm-oeiras-hourly-environment", dataset: d_cm_oeiras__hourly_environment },
      { id: "cm-oeiras-obras-municipais", dataset: d_cm_oeiras__obras_municipais },
      { id: "cm-oeiras-orcamento-participativo", dataset: d_cm_oeiras__orcamento_participativo },
      { id: "cm-oeiras-parquimetros", dataset: d_cm_oeiras__parquimetros },
      { id: "cm-oeiras-pontos-carregamento", dataset: d_cm_oeiras__pontos_carregamento },
      { id: "cm-oeiras-residuos-indiferenciados", dataset: d_cm_oeiras__residuos_indiferenciados },
    ],
  },
  {
    id: "cm-porto",
    publisher: p_cm_porto,
    datasets: [
      { id: "cm-porto-cultural-agenda", dataset: d_cm_porto__cultural_agenda },
      { id: "cm-porto-loading-zones", dataset: d_cm_porto__loading_zones },
      { id: "cm-porto-municipal-parking", dataset: d_cm_porto__municipal_parking },
      { id: "cm-porto-municipal-trees", dataset: d_cm_porto__municipal_trees },
      { id: "cm-porto-shared-micromobility-spots", dataset: d_cm_porto__shared_micromobility_spots },
    ],
  },
  {
    id: "cp",
    publisher: p_cp,
    datasets: [
      { id: "cp-gtfs", dataset: d_cp__gtfs },
    ],
  },
  {
    id: "demarca-design",
    publisher: p_demarca_design,
    datasets: [
      { id: "demarca-design-municipal-accessibility", dataset: d_demarca_design__municipal_accessibility },
    ],
  },
  {
    id: "dgeg",
    publisher: p_dgeg,
    datasets: [
      { id: "dgeg-fuel-prices", dataset: d_dgeg__fuel_prices },
    ],
  },
  {
    id: "dglab",
    publisher: p_dglab,
    datasets: [
      { id: "dglab-public-libraries-2024", dataset: d_dglab__public_libraries_2024 },
    ],
  },
  {
    id: "dgpj",
    publisher: p_dgpj,
    datasets: [
      { id: "dgpj-justice-facilities", dataset: d_dgpj__justice_facilities },
    ],
  },
  {
    id: "dgs",
    publisher: p_dgs,
    datasets: [
      { id: "dgs-primary-care-oral-health-referrals", dataset: d_dgs__primary_care_oral_health_referrals },
    ],
  },
  {
    id: "dgt",
    publisher: p_dgt,
    datasets: [
      { id: "dgt-caop-acores-central-oriental-freguesias", dataset: d_dgt__caop_acores_central_oriental_freguesias },
      { id: "dgt-caop-acores-central-oriental-municipios", dataset: d_dgt__caop_acores_central_oriental_municipios },
      { id: "dgt-caop-acores-ocidental-freguesias", dataset: d_dgt__caop_acores_ocidental_freguesias },
      { id: "dgt-caop-acores-ocidental-municipios", dataset: d_dgt__caop_acores_ocidental_municipios },
      { id: "dgt-caop-administrative-areas", dataset: d_dgt__caop_administrative_areas },
      { id: "dgt-caop-madeira-freguesias", dataset: d_dgt__caop_madeira_freguesias },
      { id: "dgt-caop-madeira-municipios", dataset: d_dgt__caop_madeira_municipios },
      { id: "dgt-crus", dataset: d_dgt__crus },
      { id: "dgt-crus-shapes", dataset: d_dgt__crus_shapes },
      { id: "dgt-fototeca-index", dataset: d_dgt__fototeca_index },
      { id: "dgt-rgn-rede-gravimetrica", dataset: d_dgt__rgn_rede_gravimetrica },
      { id: "dgt-rgn-rede-maregrafica", dataset: d_dgt__rgn_rede_maregrafica },
      { id: "dgt-rgn-rede-nivelamento", dataset: d_dgt__rgn_rede_nivelamento },
      { id: "dgt-rgn-renep-estacoes", dataset: d_dgt__rgn_renep_estacoes },
      { id: "dgt-rgn-vertices-geodesicos", dataset: d_dgt__rgn_vertices_geodesicos },
      { id: "dgt-serras-cumes-principais", dataset: d_dgt__serras_cumes_principais },
      { id: "dgt-serras-principais", dataset: d_dgt__serras_principais },
      { id: "dgt-serras-toponimicas", dataset: d_dgt__serras_toponimicas },
      { id: "dgt-sgifr-pontos", dataset: d_dgt__sgifr_pontos },
      { id: "dgt-snit-medidas-preventivas", dataset: d_dgt__snit_medidas_preventivas },
      { id: "dgt-snit-paap", dataset: d_dgt__snit_paap },
      { id: "dgt-snit-paqat", dataset: d_dgt__snit_paqat },
      { id: "dgt-snit-pdm", dataset: d_dgt__snit_pdm },
      { id: "dgt-snit-peap", dataset: d_dgt__snit_peap },
      { id: "dgt-snit-pfn", dataset: d_dgt__snit_pfn },
      { id: "dgt-snit-pgrh", dataset: d_dgt__snit_pgrh },
      { id: "dgt-snit-pgri", dataset: d_dgt__snit_pgri },
      { id: "dgt-snit-piot", dataset: d_dgt__snit_piot },
      { id: "dgt-snit-pna", dataset: d_dgt__snit_pna },
      { id: "dgt-snit-pnpot", dataset: d_dgt__snit_pnpot },
      { id: "dgt-snit-poaap", dataset: d_dgt__snit_poaap },
      { id: "dgt-snit-poap", dataset: d_dgt__snit_poap },
      { id: "dgt-snit-poc", dataset: d_dgt__snit_poc },
      { id: "dgt-snit-pooc", dataset: d_dgt__snit_pooc },
      { id: "dgt-snit-pp", dataset: d_dgt__snit_pp },
      { id: "dgt-snit-prgp", dataset: d_dgt__snit_prgp },
      { id: "dgt-snit-prn", dataset: d_dgt__snit_prn },
      { id: "dgt-snit-prof", dataset: d_dgt__snit_prof },
      { id: "dgt-snit-prot-plano", dataset: d_dgt__snit_prot_plano },
      { id: "dgt-snit-prot-programa", dataset: d_dgt__snit_prot_programa },
      { id: "dgt-snit-pszaer", dataset: d_dgt__snit_pszaer },
      { id: "dgt-snit-pu", dataset: d_dgt__snit_pu },
      { id: "dgt-snit-rede-natura", dataset: d_dgt__snit_rede_natura },
      { id: "dgt-srup-aeronautica", dataset: d_dgt__srup_aeronautica },
      { id: "dgt-srup-albufeiras", dataset: d_dgt__srup_albufeiras },
      { id: "dgt-srup-areas-protegidas", dataset: d_dgt__srup_areas_protegidas },
      { id: "dgt-srup-arvores-interesse-publico-areas", dataset: d_dgt__srup_arvores_interesse_publico_areas },
      { id: "dgt-srup-arvores-interesse-publico-pontos", dataset: d_dgt__srup_arvores_interesse_publico_pontos },
      { id: "dgt-srup-captacoes-aguas-subterraneas", dataset: d_dgt__srup_captacoes_aguas_subterraneas },
      { id: "dgt-srup-defesa-nacional", dataset: d_dgt__srup_defesa_nacional },
      { id: "dgt-srup-defesa-nacional-zonas", dataset: d_dgt__srup_defesa_nacional_zonas },
      { id: "dgt-srup-estacoes-ferroviarias", dataset: d_dgt__srup_estacoes_ferroviarias },
      { id: "dgt-srup-marcos-geodesicos", dataset: d_dgt__srup_marcos_geodesicos },
      { id: "dgt-srup-rede-eletrica", dataset: d_dgt__srup_rede_eletrica },
      { id: "dgt-srup-rede-ferroviaria", dataset: d_dgt__srup_rede_ferroviaria },
      { id: "dgt-srup-rede-natura-zec", dataset: d_dgt__srup_rede_natura_zec },
      { id: "dgt-srup-rede-natura-zpe", dataset: d_dgt__srup_rede_natura_zpe },
      { id: "dgt-srup-rede-rodoviaria", dataset: d_dgt__srup_rede_rodoviaria },
      { id: "dgt-srup-reserva-agricola", dataset: d_dgt__srup_reserva_agricola },
      { id: "dgt-srup-reserva-ecologica-areas", dataset: d_dgt__srup_reserva_ecologica_areas },
      { id: "dgt-srup-reserva-ecologica-linhas", dataset: d_dgt__srup_reserva_ecologica_linhas },
    ],
  },
  {
    id: "e-redes",
    publisher: p_e_redes,
    datasets: [
      { id: "e-redes-active-smart-meter-contracts", dataset: d_e_redes__active_smart_meter_contracts },
      { id: "e-redes-consumption-forecast", dataset: d_e_redes__consumption_forecast },
      { id: "e-redes-contracts-by-power-band", dataset: d_e_redes__contracts_by_power_band },
      { id: "e-redes-distribution-injection", dataset: d_e_redes__distribution_injection },
      { id: "e-redes-districts", dataset: d_e_redes__districts },
      { id: "e-redes-energy-communities", dataset: d_e_redes__energy_communities },
      { id: "e-redes-ev-charging-connections", dataset: d_e_redes__ev_charging_connections },
      { id: "e-redes-ev-grid-connection-requests", dataset: d_e_redes__ev_grid_connection_requests },
      { id: "e-redes-grid-reception-capacity", dataset: d_e_redes__grid_reception_capacity },
      { id: "e-redes-hourly-consumption-lisbon-porto-postcodes", dataset: d_e_redes__hourly_consumption_lisbon_porto_postcodes },
      { id: "e-redes-monthly-postal-consumption", dataset: d_e_redes__monthly_postal_consumption },
      { id: "e-redes-municipal-contracted-capacity", dataset: d_e_redes__municipal_contracted_capacity },
      { id: "e-redes-municipal-monthly-consumption", dataset: d_e_redes__municipal_monthly_consumption },
      { id: "e-redes-municipal-street-lighting", dataset: d_e_redes__municipal_street_lighting },
      { id: "e-redes-municipal-tariff-consumption", dataset: d_e_redes__municipal_tariff_consumption },
      { id: "e-redes-municipal-transformer-capacity", dataset: d_e_redes__municipal_transformer_capacity },
      { id: "e-redes-national-consumption", dataset: d_e_redes__national_consumption },
      { id: "e-redes-national-production", dataset: d_e_redes__national_production },
      { id: "e-redes-scheduled-interruptions", dataset: d_e_redes__scheduled_interruptions },
      { id: "e-redes-self-consumption-exported-energy", dataset: d_e_redes__self_consumption_exported_energy },
      { id: "e-redes-self-consumption-installations", dataset: d_e_redes__self_consumption_installations },
      { id: "e-redes-service-continuity", dataset: d_e_redes__service_continuity },
      { id: "e-redes-substation-load", dataset: d_e_redes__substation_load },
    ],
  },
  {
    id: "effis-jrc",
    publisher: p_effis_jrc,
    datasets: [
      { id: "effis-jrc-effis-portugal-recent-burnt-areas", dataset: d_effis_jrc__effis_portugal_recent_burnt_areas },
    ],
  },
  {
    id: "eurostat",
    publisher: p_eurostat,
    datasets: [
      { id: "eurostat-portugal-economic-sentiment", dataset: d_eurostat__portugal_economic_sentiment },
      { id: "eurostat-portugal-electricity-generation", dataset: d_eurostat__portugal_electricity_generation },
      { id: "eurostat-portugal-hicp-annual-rate", dataset: d_eurostat__portugal_hicp_annual_rate },
      { id: "eurostat-portugal-house-price-index", dataset: d_eurostat__portugal_house_price_index },
      { id: "eurostat-portugal-industrial-production", dataset: d_eurostat__portugal_industrial_production },
      { id: "eurostat-portugal-long-term-interest-rate", dataset: d_eurostat__portugal_long_term_interest_rate },
      { id: "eurostat-portugal-monthly-unemployment", dataset: d_eurostat__portugal_monthly_unemployment },
      { id: "eurostat-portugal-quarterly-gdp", dataset: d_eurostat__portugal_quarterly_gdp },
      { id: "eurostat-portugal-retail-trade-volume", dataset: d_eurostat__portugal_retail_trade_volume },
      { id: "eurostat-portugal-tourism-nights", dataset: d_eurostat__portugal_tourism_nights },
    ],
  },
  {
    id: "fertagus",
    publisher: p_fertagus,
    datasets: [
      { id: "fertagus-gtfs", dataset: d_fertagus__gtfs },
    ],
  },
  {
    id: "horarios-do-funchal",
    publisher: p_horarios_do_funchal,
    datasets: [
      { id: "horarios-do-funchal-gtfs", dataset: d_horarios_do_funchal__gtfs },
    ],
  },
  {
    id: "impic",
    publisher: p_impic,
    datasets: [
      { id: "impic-base-contract-modifications-2026", dataset: d_impic__base_contract_modifications_2026 },
      { id: "impic-base-procurement-entities", dataset: d_impic__base_procurement_entities },
      { id: "impic-base-procurement-notices-2026", dataset: d_impic__base_procurement_notices_2026 },
    ],
  },
  {
    id: "ine",
    publisher: p_ine,
    datasets: [
      { id: "ine-airport-passengers-embarked", dataset: d_ine__airport_passengers_embarked },
      { id: "ine-average-monthly-earnings", dataset: d_ine__average_monthly_earnings },
      { id: "ine-broadband-accesses-per-100", dataset: d_ine__broadband_accesses_per_100 },
      { id: "ine-broadband-data-traffic", dataset: d_ine__broadband_data_traffic },
      { id: "ine-consumer-price-index", dataset: d_ine__consumer_price_index },
      { id: "ine-crime-rate", dataset: d_ine__crime_rate },
      { id: "ine-declared-income-per-inhabitant", dataset: d_ine__declared_income_per_inhabitant },
      { id: "ine-employment-rate", dataset: d_ine__employment_rate },
      { id: "ine-fixed-broadband-accesses", dataset: d_ine__fixed_broadband_accesses },
      { id: "ine-fixed-broadband-accesses-per-100", dataset: d_ine__fixed_broadband_accesses_per_100 },
      { id: "ine-fixed-telephone-clients", dataset: d_ine__fixed_telephone_clients },
      { id: "ine-heavy-rail-passengers", dataset: d_ine__heavy_rail_passengers },
      { id: "ine-house-price-index", dataset: d_ine__house_price_index },
      { id: "ine-household-broadband-access", dataset: d_ine__household_broadband_access },
      { id: "ine-household-income-gini", dataset: d_ine__household_income_gini },
      { id: "ine-household-income-p90-p10", dataset: d_ine__household_income_p90_p10 },
      { id: "ine-housing-transactions-value", dataset: d_ine__housing_transactions_value },
      { id: "ine-industrial-production-index", dataset: d_ine__industrial_production_index },
      { id: "ine-live-births", dataset: d_ine__live_births },
      { id: "ine-median-bank-valuation", dataset: d_ine__median_bank_valuation },
      { id: "ine-median-home-sale-price", dataset: d_ine__median_home_sale_price },
      { id: "ine-median-household-income-after-tax", dataset: d_ine__median_household_income_after_tax },
      { id: "ine-resident-population", dataset: d_ine__resident_population },
      { id: "ine-taxpayer-income-distribution", dataset: d_ine__taxpayer_income_distribution },
      { id: "ine-tourism-overnight-stays", dataset: d_ine__tourism_overnight_stays },
      { id: "ine-unemployment-rate", dataset: d_ine__unemployment_rate },
    ],
  },
  {
    id: "ioda",
    publisher: p_ioda,
    datasets: [
      { id: "ioda-portugal-internet-outages", dataset: d_ioda__portugal_internet_outages },
    ],
  },
  {
    id: "ipma",
    publisher: p_ipma,
    datasets: [
      { id: "ipma-daily-forecast", dataset: d_ipma__daily_forecast },
      { id: "ipma-fire-risk", dataset: d_ipma__fire_risk },
      { id: "ipma-municipal-climate", dataset: d_ipma__municipal_climate },
      { id: "ipma-sea-forecast", dataset: d_ipma__sea_forecast },
      { id: "ipma-seismic", dataset: d_ipma__seismic },
      { id: "ipma-shellfish-restrictions", dataset: d_ipma__shellfish_restrictions },
      { id: "ipma-station-observations", dataset: d_ipma__station_observations },
      { id: "ipma-uv-index", dataset: d_ipma__uv_index },
      { id: "ipma-weather-warnings", dataset: d_ipma__weather_warnings },
    ],
  },
  {
    id: "lneg",
    publisher: p_lneg,
    datasets: [
      { id: "lneg-falhas-geologicas", dataset: d_lneg__falhas_geologicas },
      { id: "lneg-ocorrencias-minerais", dataset: d_lneg__ocorrencias_minerais },
      { id: "lneg-pontos-de-agua", dataset: d_lneg__pontos_de_agua },
      { id: "lneg-sistemas-aquiferos", dataset: d_lneg__sistemas_aquiferos },
      { id: "lneg-sondagens", dataset: d_lneg__sondagens },
    ],
  },
  {
    id: "mare",
    publisher: p_mare,
    datasets: [
      { id: "mare-network", dataset: d_mare__network },
    ],
  },
  {
    id: "metro-do-porto",
    publisher: p_metro_do_porto,
    datasets: [
      { id: "metro-do-porto-gtfs", dataset: d_metro_do_porto__gtfs },
    ],
  },
  {
    id: "metropolitano-de-lisboa",
    publisher: p_metropolitano_de_lisboa,
    datasets: [
      { id: "metropolitano-de-lisboa-gtfs", dataset: d_metropolitano_de_lisboa__gtfs },
      { id: "metropolitano-de-lisboa-network", dataset: d_metropolitano_de_lisboa__network },
    ],
  },
  {
    id: "nasa-firms",
    publisher: p_nasa_firms,
    datasets: [
      { id: "nasa-firms-portugal-thermal-anomalies", dataset: d_nasa_firms__portugal_thermal_anomalies },
    ],
  },
  {
    id: "nasa-power",
    publisher: p_nasa_power,
    datasets: [
      { id: "nasa-power-portugal-solar-resource", dataset: d_nasa_power__portugal_solar_resource },
    ],
  },
  {
    id: "omie",
    publisher: p_omie,
    datasets: [
      { id: "omie-day-ahead-prices", dataset: d_omie__day_ahead_prices },
    ],
  },
  {
    id: "peeringdb",
    publisher: p_peeringdb,
    datasets: [
      { id: "peeringdb-portugal-exchanges", dataset: d_peeringdb__portugal_exchanges },
    ],
  },
  {
    id: "porto-digital",
    publisher: p_porto_digital,
    datasets: [
      { id: "porto-digital-urban-sensors", dataset: d_porto_digital__urban_sensors },
    ],
  },
  {
    id: "ren",
    publisher: p_ren,
    datasets: [
      { id: "ren-electricity-system", dataset: d_ren__electricity_system },
      { id: "ren-gas-system", dataset: d_ren__gas_system },
    ],
  },
  {
    id: "ribatejana",
    publisher: p_ribatejana,
    datasets: [
      { id: "ribatejana-network", dataset: d_ribatejana__network },
    ],
  },
  {
    id: "ripe-ncc",
    publisher: p_ripe_ncc,
    datasets: [
      { id: "ripe-ncc-atlas-portugal", dataset: d_ripe_ncc__atlas_portugal },
      { id: "ripe-ncc-portugal-internet-resources", dataset: d_ripe_ncc__portugal_internet_resources },
    ],
  },
  {
    id: "sns-transparencia",
    publisher: p_sns_transparencia,
    datasets: [
      { id: "sns-transparencia-births-and-caesareans", dataset: d_sns_transparencia__births_and_caesareans },
      { id: "sns-transparencia-blood-collection", dataset: d_sns_transparencia__blood_collection },
      { id: "sns-transparencia-cancer-screening", dataset: d_sns_transparencia__cancer_screening },
      { id: "sns-transparencia-continuing-care-waiting", dataset: d_sns_transparencia__continuing_care_waiting },
      { id: "sns-transparencia-daily-death-certificates", dataset: d_sns_transparencia__daily_death_certificates },
      { id: "sns-transparencia-dispensed-medicines", dataset: d_sns_transparencia__dispensed_medicines },
      { id: "sns-transparencia-emergency-calls-transferred-sns24", dataset: d_sns_transparencia__emergency_calls_transferred_sns24 },
      { id: "sns-transparencia-emergency-triage", dataset: d_sns_transparencia__emergency_triage },
      { id: "sns-transparencia-first-consultations-within-target", dataset: d_sns_transparencia__first_consultations_within_target },
      { id: "sns-transparencia-generic-medicine-dispensing", dataset: d_sns_transparencia__generic_medicine_dispensing },
      { id: "sns-transparencia-health-framework-agreements", dataset: d_sns_transparencia__health_framework_agreements },
      { id: "sns-transparencia-health-procurement", dataset: d_sns_transparencia__health_procurement },
      { id: "sns-transparencia-hospital-beds-by-type", dataset: d_sns_transparencia__hospital_beds_by_type },
      { id: "sns-transparencia-hospital-emergency-attendances", dataset: d_sns_transparencia__hospital_emergency_attendances },
      { id: "sns-transparencia-hospital-occupancy", dataset: d_sns_transparencia__hospital_occupancy },
      { id: "sns-transparencia-icaro-heat-index", dataset: d_sns_transparencia__icaro_heat_index },
      { id: "sns-transparencia-inem-dispatches", dataset: d_sns_transparencia__inem_dispatches },
      { id: "sns-transparencia-inem-emergency-calls", dataset: d_sns_transparencia__inem_emergency_calls },
      { id: "sns-transparencia-inem-occurrences-by-priority", dataset: d_sns_transparencia__inem_occurrences_by_priority },
      { id: "sns-transparencia-legionella-environmental-monitoring", dataset: d_sns_transparencia__legionella_environmental_monitoring },
      { id: "sns-transparencia-licensed-public-defibrillator-programmes", dataset: d_sns_transparencia__licensed_public_defibrillator_programmes },
      { id: "sns-transparencia-lvt-hospital-morbidity-mortality", dataset: d_sns_transparencia__lvt_hospital_morbidity_mortality },
      { id: "sns-transparencia-medical-specialty-training-vacancies", dataset: d_sns_transparencia__medical_specialty_training_vacancies },
      { id: "sns-transparencia-medicine-package-prices", dataset: d_sns_transparencia__medicine_package_prices },
      { id: "sns-transparencia-newborn-screening", dataset: d_sns_transparencia__newborn_screening },
      { id: "sns-transparencia-poison-information-calls", dataset: d_sns_transparencia__poison_information_calls },
      { id: "sns-transparencia-pregnancy-line-triage", dataset: d_sns_transparencia__pregnancy_line_triage },
      { id: "sns-transparencia-primary-care-consultation-access", dataset: d_sns_transparencia__primary_care_consultation_access },
      { id: "sns-transparencia-primary-care-flu-consultations", dataset: d_sns_transparencia__primary_care_flu_consultations },
      { id: "sns-transparencia-psychology-consultations", dataset: d_sns_transparencia__psychology_consultations },
      { id: "sns-transparencia-seasonal-flu-vaccination-coverage", dataset: d_sns_transparencia__seasonal_flu_vaccination_coverage },
      { id: "sns-transparencia-sickness-self-declarations", dataset: d_sns_transparencia__sickness_self_declarations },
      { id: "sns-transparencia-supplier-debt-and-arrears", dataset: d_sns_transparencia__supplier_debt_and_arrears },
      { id: "sns-transparencia-surgery-waiting-target", dataset: d_sns_transparencia__surgery_waiting_target },
    ],
  },
  {
    id: "stcp",
    publisher: p_stcp,
    datasets: [
      { id: "stcp-gtfs", dataset: d_stcp__gtfs },
      { id: "stcp-porto-stcp-bus-positions", dataset: d_stcp__porto_stcp_bus_positions },
    ],
  },
  {
    id: "tcb",
    publisher: p_tcb,
    datasets: [
      { id: "tcb-barreiro-gtfs", dataset: d_tcb__barreiro_gtfs },
    ],
  },
  {
    id: "tub-braga",
    publisher: p_tub_braga,
    datasets: [
      { id: "tub-braga-gtfs", dataset: d_tub_braga__gtfs },
    ],
  },
  {
    id: "tubabike",
    publisher: p_tubabike,
    datasets: [
      { id: "tubabike-barcelos", dataset: d_tubabike__barcelos },
    ],
  },
  {
    id: "usgs",
    publisher: p_usgs,
    datasets: [
      { id: "usgs-portugal-earthquakes", dataset: d_usgs__portugal_earthquakes },
    ],
  },
];
