// Generated by `pnpm packages:sync` from the parliament library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { PARLIAMENT_DEPLOYMENT, PARLIAMENT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/parliament";

export default libraryGatekeeper<Env>(PARLIAMENT_DEPLOYMENT, PARLIAMENT_EXAMPLES);
