// Generated by `pnpm packages:sync` from the udata library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { UDATA_DEPLOYMENT, UDATA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/udata";

export default libraryGatekeeper<Env>(UDATA_DEPLOYMENT, UDATA_EXAMPLES);
