// Generated by `pnpm packages:sync` from the gbfs library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { GBFS_DEPLOYMENT, GBFS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/gbfs";

export default libraryGatekeeper<Env>(GBFS_DEPLOYMENT, GBFS_EXAMPLES);
