// Generated by `pnpm packages:sync` from the myinfo library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { MYINFO_DEPLOYMENT, MYINFO_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/myinfo";

export default libraryGatekeeper<Env>(MYINFO_DEPLOYMENT, MYINFO_EXAMPLES);
