// Generated by `pnpm packages:sync` from the feeds whose first topic is energy; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { DGEG_DEPLOYMENT, DGEG_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/dgeg";
import { EUROSTAT_DEPLOYMENT, EUROSTAT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/eurostat";
import { OMIE_DEPLOYMENT, OMIE_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/omie";
import { OPENDATASOFT_DEPLOYMENT, OPENDATASOFT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/opendatasoft";
import { REN_DEPLOYMENT, REN_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ren";

export default topicGatekeeper<Env>(
  "energy",
  [DGEG_DEPLOYMENT, EUROSTAT_DEPLOYMENT, OMIE_DEPLOYMENT, OPENDATASOFT_DEPLOYMENT, REN_DEPLOYMENT],
  [...DGEG_EXAMPLES, ...EUROSTAT_EXAMPLES, ...OMIE_EXAMPLES, ...OPENDATASOFT_EXAMPLES, ...REN_EXAMPLES],
);
