// Generated by `pnpm packages:sync` from the bpstat library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { BPSTAT_DEPLOYMENT, BPSTAT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/bpstat";

export default libraryGatekeeper<Env>(BPSTAT_DEPLOYMENT, BPSTAT_EXAMPLES);
