// Generated by `pnpm packages:sync` from the eurostat library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { EUROSTAT_DEPLOYMENT, EUROSTAT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/eurostat";

export default libraryGatekeeper<Env>(EUROSTAT_DEPLOYMENT, EUROSTAT_EXAMPLES);
