// Generated by `pnpm packages:sync` from the feeds whose first topic is health; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { OPENDATASOFT_DEPLOYMENT, OPENDATASOFT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/opendatasoft";
import { UDATA_DEPLOYMENT, UDATA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/udata";

export default topicGatekeeper<Env>("health", [OPENDATASOFT_DEPLOYMENT, UDATA_DEPLOYMENT], [...OPENDATASOFT_EXAMPLES, ...UDATA_EXAMPLES]);
