// Generated by `pnpm packages:sync` from the ogc library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { OGC_DEPLOYMENT, OGC_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/ogc";

export default libraryGatekeeper<Env>(OGC_DEPLOYMENT, OGC_EXAMPLES);
