// Generated by `pnpm packages:sync` from the feeds whose first topic is government; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { PARLIAMENT_DEPLOYMENT, PARLIAMENT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/parliament";
import { UDATA_DEPLOYMENT, UDATA_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/udata";

export default topicGatekeeper<Env>("government", [PARLIAMENT_DEPLOYMENT, UDATA_DEPLOYMENT], [...PARLIAMENT_EXAMPLES, ...UDATA_EXAMPLES]);
