// Generated by `pnpm packages:sync` from the ine library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { INE_DEPLOYMENT, INE_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ine";

export default libraryGatekeeper<Env>(INE_DEPLOYMENT, INE_EXAMPLES);
