// Generated by `pnpm packages:sync` from the gtfs library and its examples; do not edit.
import { libraryGatekeeper } from "@open-data-pt/gatekeeper-shared/library-worker";
import { GTFS_DEPLOYMENT, GTFS_EXAMPLES } from "@open-data-pt/gatekeeper-shared/formats/gtfs";

export default libraryGatekeeper<Env>(GTFS_DEPLOYMENT, GTFS_EXAMPLES);
