/**
 * Write the index of the Gatekeeper's publisher folders.
 *
 *   pnpm catalog            rewrite apps/gatekeeper/src/catalog/folders.generated.ts
 *   pnpm catalog --check    fail when it no longer matches the folders
 *
 * A publisher is a folder under `apps/gatekeeper/src/publishers/`, and each of
 * their datasets a file under its `datasets/`. The Worker's bundler cannot list
 * a directory, so this script does it once and writes the imports down; a test
 * runs `--check` so a folder added without it fails before it ships.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLISHERS = join(ROOT, "apps/gatekeeper/src/publishers");
export const INDEX_PATH = join(ROOT, "apps/gatekeeper/src/catalog/folders.generated.ts");

/** A key is lowercase words joined by hyphens: what a folder or a file may be called. */
const KEY = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const identifier = (key: string) => key.replaceAll("-", "_");

/** The index as the folders say it should be. */
export function catalogIndex(): string {
  const publishers = readdirSync(PUBLISHERS, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(PUBLISHERS, entry.name, "index.ts")))
    .map((entry) => entry.name)
    .toSorted();
  const imports: string[] = [];
  const folders: string[] = [];
  for (const publisher of publishers) {
    if (!KEY.test(publisher)) throw new Error(`A publisher folder is named for its key: ${publisher}`);
    imports.push(`import { PUBLISHER as p_${identifier(publisher)} } from "../publishers/${publisher}";`);
    const datasetsDir = join(PUBLISHERS, publisher, "datasets");
    const files = existsSync(datasetsDir)
      ? readdirSync(datasetsDir)
          .filter((file) => file.endsWith(".ts"))
          .map((file) => file.slice(0, -3))
          .toSorted()
      : [];
    const datasets: string[] = [];
    for (const file of files) {
      if (!KEY.test(file)) throw new Error(`A dataset file is named for its key: ${publisher}/datasets/${file}.ts`);
      const alias = `d_${identifier(publisher)}__${identifier(file)}`;
      imports.push(`import { DATASET as ${alias} } from "../publishers/${publisher}/datasets/${file}";`);
      datasets.push(`      { id: "${publisher}-${file}", dataset: ${alias} },`);
    }
    folders.push(`  {\n    id: "${publisher}",\n    publisher: p_${identifier(publisher)},\n    datasets: [\n${datasets.join("\n")}\n    ],\n  },`);
  }
  return [
    "// Generated by `pnpm catalog` from the folders under src/publishers. Do not edit it by hand: add a folder or a file and run it.",
    'import type { DatasetDefinition, PublisherDefinition } from "./define";',
    ...imports,
    "",
    "/** One publisher folder: its key, what its `index.ts` declares, and every dataset file under it, keyed. */",
    "export interface PublisherFolder {",
    "  id: string;",
    "  publisher: PublisherDefinition;",
    "  datasets: ReadonlyArray<{ id: string; dataset: DatasetDefinition }>;",
    "}",
    "",
    "export const PUBLISHER_FOLDERS: readonly PublisherFolder[] = [",
    ...folders,
    "];",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const wanted = catalogIndex();
  if (process.argv.includes("--check")) {
    const current = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, "utf8") : "";
    if (current !== wanted) {
      console.error("apps/gatekeeper/src/catalog/folders.generated.ts is stale: run `pnpm catalog`.");
      process.exit(1);
    }
  } else {
    writeFileSync(INDEX_PATH, wanted);
  }
}
