/**
 * Write the index of the Gatekeeper's publisher folders.
 *
 *   pnpm catalog            rewrite apps/gatekeeper/src/catalog/folders.generated.ts
 *   pnpm catalog --check    fail when it no longer matches the folders
 *
 * A publisher is a folder under `apps/gatekeeper/src/publishers/` with an
 * `index.ts`, which lists every feed of theirs from the files under its
 * `feeds/`. The Worker's bundler cannot list a directory, so this script lists
 * the publisher folders once and writes the imports down; a test runs
 * `--check`, so a folder added without it fails before it ships, and another
 * holds every feed file to being in its publisher's list.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLISHERS = join(ROOT, "apps/gatekeeper/src/publishers");
export const INDEX_PATH = join(ROOT, "apps/gatekeeper/src/catalog/folders.generated.ts");

/** A key is lowercase words joined by hyphens: what a folder or a file may be called. */
const KEY = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const identifier = (key: string) => key.replaceAll("-", "_");

/** The index as the folders say it should be. */
export function catalogIndex(): string {
  const publishers = readdirSync(PUBLISHERS, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(PUBLISHERS, entry.name, "index.ts")))
    .map((entry) => entry.name)
    .toSorted();
  const imports: string[] = [];
  const folders: string[] = [];
  for (const publisher of publishers) {
    if (!KEY.test(publisher)) throw new Error(`A publisher folder is named for its key: ${publisher}`);
    imports.push(`import { PUBLISHER as ${identifier(publisher)} } from "#/publishers/${publisher}/index";`);
    folders.push(`  { id: "${publisher}", publisher: ${identifier(publisher)} },`);
  }
  return [
    "// Generated by `pnpm catalog` from the folders under src/publishers. Do not edit it by hand: add a folder and run it.",
    'import type { PublisherDefinition } from "#/catalog/define";',
    ...imports,
    "",
    "/** One publisher folder: its key, and what its `index.ts` declares, feeds and all. */",
    "export interface PublisherFolder {",
    "  id: string;",
    "  publisher: PublisherDefinition;",
    "}",
    "",
    "export const PUBLISHER_FOLDERS: readonly PublisherFolder[] = [",
    ...folders,
    "];",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const wanted = catalogIndex();
  if (process.argv.includes("--check")) {
    const current = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, "utf8") : "";
    if (current !== wanted) {
      console.error("apps/gatekeeper/src/catalog/folders.generated.ts is stale: run `pnpm catalog`.");
      process.exit(1);
    }
  } else {
    writeFileSync(INDEX_PATH, wanted);
  }
}
