/**
 * Write the index of the Gatekeeper's publisher folders.
 *
 *   pnpm catalog            rewrite apps/gatekeeper/src/catalog/folders.generated.ts
 *   pnpm catalog --check    fail when it no longer matches the folders
 *
 * A publisher is a folder under `apps/gatekeeper/src/publishers/`; each of their
 * datasets is a folder under its `datasets/`, with an `index.ts` and one file
 * per feed. The Worker's bundler cannot list
 * a directory, so this script does it once and writes the imports down; a test
 * runs `--check` so a folder added without it fails before it ships.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLISHERS = join(ROOT, "apps/gatekeeper/src/publishers");
export const INDEX_PATH = join(ROOT, "apps/gatekeeper/src/catalog/folders.generated.ts");

/** A key is lowercase words joined by hyphens: what a folder or a file may be called. */
const KEY = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const identifier = (key: string) => key.replaceAll("-", "_");

/** The index as the folders say it should be. */
export function catalogIndex(): string {
  const publishers = readdirSync(PUBLISHERS, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(PUBLISHERS, entry.name, "index.ts")))
    .map((entry) => entry.name)
    .toSorted();
  const imports: string[] = [];
  const folders: string[] = [];
  for (const publisher of publishers) {
    if (!KEY.test(publisher)) throw new Error(`A publisher folder is named for its key: ${publisher}`);
    imports.push(`import { PUBLISHER as p_${identifier(publisher)} } from "#/publishers/${publisher}/index";`);
    const datasetsDir = join(PUBLISHERS, publisher, "datasets");
    const entries = existsSync(datasetsDir) ? readdirSync(datasetsDir, { withFileTypes: true }).toSorted((a, b) => a.name.localeCompare(b.name)) : [];
    const datasets: string[] = [];
    for (const entry of entries) {
      // A dataset is a folder: `<name>/index.ts`, and one file per feed beside it.
      if (!entry.isDirectory()) throw new Error(`A dataset is a folder, not a file: ${publisher}/datasets/${entry.name}`);
      const name = entry.name;
      if (!KEY.test(name)) throw new Error(`A dataset is named for its key: ${publisher}/datasets/${name}`);
      const alias = `d_${identifier(publisher)}__${identifier(name)}`;
      if (!existsSync(join(datasetsDir, name, "index.ts"))) throw new Error(`A dataset folder has an index.ts: ${publisher}/datasets/${name}`);
      imports.push(`import { DATASET as ${alias} } from "#/publishers/${publisher}/datasets/${name}/index";`);
      const feeds = readdirSync(join(datasetsDir, name))
        .filter((file) => file.endsWith(".ts") && file !== "index.ts")
        .map((file) => file.slice(0, -3))
        .toSorted();
      if (feeds.length === 0) throw new Error(`A dataset folder has at least one feed file: ${publisher}/datasets/${name}`);
      const feedAliases: string[] = [];
      for (const feed of feeds) {
        if (!KEY.test(feed)) throw new Error(`A feed file is named for its feed: ${publisher}/datasets/${name}/${feed}.ts`);
        const feedAlias = `f_${identifier(publisher)}__${identifier(name)}__${identifier(feed)}`;
        imports.push(`import { FEED as ${feedAlias} } from "#/publishers/${publisher}/datasets/${name}/${feed}";`);
        feedAliases.push(feedAlias);
      }
      datasets.push(`      { id: "${publisher}-${name}", dataset: ${alias}, feeds: [${feedAliases.join(", ")}] },`);
    }
    folders.push(`  {\n    id: "${publisher}",\n    publisher: p_${identifier(publisher)},\n    datasets: [\n${datasets.join("\n")}\n    ],\n  },`);
  }
  return [
    "// Generated by `pnpm catalog` from the folders under src/publishers. Do not edit it by hand: add a folder or a file and run it.",
    'import type { DatasetDefinition, PublisherDefinition } from "#/catalog/define";',
    'import type { RunnableFeed } from "#/library";',
    ...imports,
    "",
    "/** One publisher folder: its key, what its `index.ts` declares, and every dataset folder under it with its feeds, keyed. */",
    "export interface PublisherFolder {",
    "  id: string;",
    "  publisher: PublisherDefinition;",
    "  datasets: ReadonlyArray<{ id: string; dataset: DatasetDefinition; feeds: readonly RunnableFeed[] }>;",
    "}",
    "",
    "export const PUBLISHER_FOLDERS: readonly PublisherFolder[] = [",
    ...folders,
    "];",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const wanted = catalogIndex();
  if (process.argv.includes("--check")) {
    const current = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, "utf8") : "";
    if (current !== wanted) {
      console.error("apps/gatekeeper/src/catalog/folders.generated.ts is stale: run `pnpm catalog`.");
      process.exit(1);
    }
  } else {
    writeFileSync(INDEX_PATH, wanted);
  }
}
