// Generated by `pnpm packages:sync` from the feeds whose first topic is economy; do not edit.
import { topicGatekeeper } from "@open-data-pt/gatekeeper-shared/topic-worker";
import { BPSTAT_DEPLOYMENT, BPSTAT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/bpstat";
import { EUROSTAT_DEPLOYMENT, EUROSTAT_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/eurostat";
import { INE_DEPLOYMENT, INE_EXAMPLES } from "@open-data-pt/gatekeeper-shared/sources/ine";

export default topicGatekeeper<Env>("economy", [BPSTAT_DEPLOYMENT, EUROSTAT_DEPLOYMENT, INE_DEPLOYMENT], [...BPSTAT_EXAMPLES, ...EUROSTAT_EXAMPLES, ...INE_EXAMPLES]);
